// Edge function: func-003-send-email
// Generated by stress-generator
import { /* logger */ } from "../_shared/logger.ts";
import { /* crypto-utils */ } from "../_shared/crypto-utils.ts";
import { /* auth-helpers */ } from "../_shared/auth-helpers.ts";
import { /* helpers */ } from "./utils_0.ts";

Deno.serve(async (req: Request) => {
  try {
  // Stream response
  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    start(controller) {
      for (let i = 0; i < 5; i++) {
        controller.enqueue(encoder.encode(`data: {"chunk": ${i}, "function": "func-003-send-email"}\n\n`));
      }
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
  } catch (error) {
    console.error(`Error in func-003-send-email:`, error);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
});
