-- Migration: create_table_solvo_audax_atavus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE aegrotatio_acies_136 (
  id SERIAL PRIMARY KEY,
  vociferor_damnatio TIMESTAMPTZ,
  bibo_quaerat DOUBLE PRECISION DEFAULT 0.0,
  adsum_vulgus VARCHAR(255) NOT NULL,
  animus TIMESTAMPTZ UNIQUE,
  vulnus_torrens NUMERIC(10,2),
  aperte_valde UUID,
  tabella_tenus_absum DATE DEFAULT CURRENT_DATE,
  approbo_facere_bestia TEXT,
  depopulo_amo_infit UUID NOT NULL DEFAULT gen_random_uuid(),
  communis BYTEA,
  territo_vapulus TEXT[] NOT NULL,
  caterva_turba TEXT NOT NULL,
  vehemens_repellendus NUMERIC(10,2),
  doloremque_sponte_adhuc VARCHAR(255) NOT NULL DEFAULT 'default' UNIQUE,
  viscus BYTEA DEFAULT '\x00'::bytea,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
