-- Migration: create_table_curto_contego_decet
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE depulso_utilis_887 (
  id SERIAL PRIMARY KEY,
  cernuus_adficio_uberrime MACADDR,
  validus_ipsum_volaticus TEXT[],
  placeat_adsidue JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
