-- Migration: create_view_aro_taceo_contra
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_trepide_speculum_824 AS
SELECT a.id, a.vicissitudo_maiores_subito, a.curriculum_tabgo, b.id, b.desolo_admoneo, b.voro_carbo
FROM occaecati_dicta_611 a
CROSS JOIN derideo_coerceo_285 b
LIMIT 1000;
