-- Migration: create_table_arbitro_solvo_solvo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE dolorum_adversus_357 (
  id SERIAL PRIMARY KEY,
  cultellus_curto SMALLINT,
  adamo INT[],
  dens TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  tener TIMESTAMPTZ,
  capillus SMALLINT,
  cunctatio_itaque BOOLEAN,
  demens JSONB DEFAULT '{}'::jsonb,
  calco_curo_iusto MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  amo_currus_accommodo TEXT DEFAULT 'default_text',
  defetiscor_cumque JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  fuga_verto_346_id INTEGER REFERENCES fuga_verto_346(id)
);
