-- Migration: create_index_vilitas_vulpes_cilicium
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_conicio_centum_966_circumvenio_barba_averto_amo_ultra ON conicio_centum_966 (circumvenio_barba, averto_amo_ultra) WHERE circumvenio_barba IS NOT NULL;
