-- Migration: create_table_censura_thema_colo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE coerceo_suggero_68 (
  id SERIAL PRIMARY KEY,
  quas_adipisci MACADDR NOT NULL,
  tempora TEXT,
  statua_decumbo_certus TEXT[],
  suadeo_bos_agnitio REAL NOT NULL DEFAULT 0.0,
  custodia INT[],
  vorago DATE NOT NULL DEFAULT CURRENT_DATE,
  solio TIMESTAMP NOT NULL,
  ustilo INET NOT NULL,
  apostolus_adduco INT[] NOT NULL,
  antea REAL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  bellum_correptius_485_id INTEGER REFERENCES bellum_correptius_485(id)
);
