-- Migration: create_index_cavus_praesentium_vesica
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_aequitas_temporibus_486_quia_dens_natus_triumphus ON aequitas_temporibus_486 (quia_dens, natus_triumphus) WHERE quia_dens IS NOT NULL;
