-- Migration: create_table_theca_ab_cimentarius
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE cunabula_ducimus_746 (
  id SERIAL PRIMARY KEY,
  crastinus TIMESTAMP,
  quia_campana BYTEA,
  vacuus JSON NOT NULL,
  tardus_damnatio JSON DEFAULT '{}'::json,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  quae_ustulo_571_id INTEGER REFERENCES quae_ustulo_571(id)
);
