-- Migration: create_table_stabilis_corroboro_tabella
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tabgo_synagoga_165 (
  id SERIAL PRIMARY KEY,
  defungo INTEGER NOT NULL,
  absque_theologus_molestias TEXT[] DEFAULT ARRAY[]::TEXT[] UNIQUE,
  turba_coniuratio_quae JSONB NOT NULL,
  verbera_blandior_tripudio REAL NOT NULL UNIQUE,
  stipes_bos DATE,
  vilicus BYTEA,
  corpus NUMERIC(10,2),
  voluptatibus BOOLEAN NOT NULL DEFAULT false,
  aurum_defaeco BIGINT UNIQUE,
  audacia_caelum_solvo UUID DEFAULT gen_random_uuid(),
  appositus_corrumpo CIDR DEFAULT '0.0.0.0/0'::cidr,
  ea CIDR,
  maxime_cedo NUMERIC(10,2),
  tamquam_fuga_deinde BIGINT,
  arceo_distinctio_sit JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  absum_aequus_393_id INTEGER REFERENCES absum_aequus_393(id)
);
