-- Migration: create_table_absorbeo_vulpes_spiculum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE conicio_centum_966 (
  id SERIAL PRIMARY KEY,
  nisi_apud UUID NOT NULL,
  utrum_qui_modi DOUBLE PRECISION UNIQUE,
  illo_calcar TEXT[] NOT NULL,
  aperte_texo_ante INET,
  delectatio TEXT[],
  circumvenio_barba BYTEA,
  uredo_vomer DATE NOT NULL,
  averto_amo_ultra UUID NOT NULL UNIQUE,
  dedico_dolore_quidem INT[],
  stultus_appono_coepi TIMESTAMP NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
