-- Migration: create_index_magni_ullam_baiulus
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_patrocinor_usitas_946_aliquam_tamisium ON patrocinor_usitas_946 (aliquam_tamisium);
