-- Migration: create_index_tener_cognomen_tondeo
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_nisi_laudantium_561_tripudio ON nisi_laudantium_561 USING gin (tibi_centum_tremo);
