-- Migration: rls_policy_hic_commodo_approbo
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE utique_voluntarius_177 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_utique_voluntarius_177_909" ON utique_voluntarius_177 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_utique_voluntarius_177_19" ON utique_voluntarius_177 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_utique_voluntarius_177_557" ON utique_voluntarius_177 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_utique_voluntarius_177_787" ON utique_voluntarius_177 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
