-- Migration: create_view_ubi_conventus_thalassinus
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_tempus_tondeo_342 AS
SELECT a.id, a.ocer_nobis_vulariter, a.patria, b.id, b.strenuus_spes_bibo, b.xiphias_administratio
FROM tui_quaerat_563 a
CROSS JOIN quae_ustulo_571 b
LIMIT 1000;
