-- Migration: create_table_adstringo_curatio_defungo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE bene_calculus_469 (
  id SERIAL PRIMARY KEY,
  aspicio BIGINT NOT NULL,
  cibo_theologus TIMESTAMPTZ DEFAULT NOW(),
  conspergo REAL DEFAULT 0.0,
  conicio MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  magnam INET,
  quia BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  conicio_centum_966_id INTEGER REFERENCES conicio_centum_966(id)
);
