-- Migration: create_table_crux_cariosus_dedico
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE corpus_dicta_560 (
  id SERIAL PRIMARY KEY,
  placeat_numquam JSON NOT NULL DEFAULT '{}'::json UNIQUE,
  caelestis JSONB NOT NULL,
  cultellus_cruentus SMALLINT,
  adipiscor INET,
  cunabula_somniculosus_delego DOUBLE PRECISION DEFAULT 0.0,
  tollo_tabesco DOUBLE PRECISION,
  verto_adsidue_tracto TEXT,
  absorbeo_asporto_nobis BYTEA NOT NULL,
  ab_animi JSON NOT NULL,
  aestas_aureus CIDR NOT NULL,
  bellum_absum_vulpes BOOLEAN NOT NULL DEFAULT false,
  comitatus_spargo_audeo DOUBLE PRECISION DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sui_acer_419_id INTEGER REFERENCES sui_acer_419(id)
);
