-- Migration: create_index_comburo_nobis_sustineo
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_sollers_adflicto_598_administratio_basium_conservo_antea ON sollers_adflicto_598 (administratio, basium_conservo_antea);
