-- Migration: create_index_tantillus_curo_ea
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_adhaero_averto_179_basium_decet_advoco_usque_dolor_demoror ON adhaero_averto_179 (basium_decet_advoco, usque, dolor_demoror) WHERE basium_decet_advoco IS NOT NULL;
