-- Migration: trigger_function_cubo_audio_tempore
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_conor_fugiat_811()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.id IS NULL THEN
    RAISE EXCEPTION 'id cannot be null on vigor_quisquam_335';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_vigor_quisquam_335_217
  BEFORE INSERT OR UPDATE ON vigor_quisquam_335
  FOR EACH ROW EXECUTE FUNCTION fn_conor_fugiat_811();
