-- Migration: create_table_uter_caelestis_demoror
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE sulum_bellicus_307 (
  id SERIAL PRIMARY KEY,
  suggero_qui DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  cohors_vorax CIDR DEFAULT '0.0.0.0/0'::cidr UNIQUE,
  amplus JSON NOT NULL,
  distinctio_tollo CIDR NOT NULL,
  maiores BOOLEAN,
  abstergo TEXT DEFAULT 'default_text',
  vos TIMESTAMPTZ,
  clementia_libero_sumo BYTEA NOT NULL,
  curtus_saepe CIDR,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
