-- Migration: create_table_cras_absque_ciminatio
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE bardus_statua_764 (
  id SERIAL PRIMARY KEY,
  vicinus JSON NOT NULL,
  annus_caterva_torqueo NUMERIC(10,2) NOT NULL,
  adfectus_umerus_callide CIDR,
  tamen_thymum BYTEA NOT NULL,
  caritas BIGINT DEFAULT 0 UNIQUE,
  tripudio NUMERIC(10,2) UNIQUE,
  praesentium_auctus_spoliatio INET,
  aliquid SMALLINT UNIQUE,
  exercitationem_velociter TEXT[] NOT NULL,
  suffragium_ager_cuius DOUBLE PRECISION DEFAULT 0.0,
  adeo_tenus_supra TEXT[] NOT NULL,
  impedit INET NOT NULL,
  conatus_absque SMALLINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  commodo_denique_597_id INTEGER REFERENCES commodo_denique_597(id)
);
