-- Migration: create_table_somniculosus_angustus_civitas
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tondeo_repellat_388 (
  id SERIAL PRIMARY KEY,
  conitor INT[],
  advenio_arceo_absens DOUBLE PRECISION DEFAULT 0.0,
  carbo_desino REAL DEFAULT 0.0,
  incidunt_damnatio TEXT,
  turpis TEXT[] NOT NULL,
  auxilium_virgo_vulgus REAL NOT NULL,
  optio_aer DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  villa_vitium_eligendi TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  carmen_rerum_sophismata BIGINT,
  absque TIMESTAMP NOT NULL DEFAULT NOW(),
  comminor CIDR NOT NULL DEFAULT '0.0.0.0/0'::cidr,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  absum_aequus_393_id INTEGER REFERENCES absum_aequus_393(id)
);
