-- Migration: create_table_aestas_adeo_delicate
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE carpo_canonicus_193 (
  id SERIAL PRIMARY KEY,
  tracto BIGINT DEFAULT 0,
  voluptatum INET DEFAULT '0.0.0.0'::inet,
  aufero_minus_torrens INET NOT NULL,
  modi_texo REAL NOT NULL DEFAULT 0.0,
  celebrer SMALLINT NOT NULL DEFAULT 0,
  casso_casus_quo INET NOT NULL,
  ver_titulus MACADDR,
  antiquus_crustulum_cernuus TIMESTAMPTZ UNIQUE,
  ater NUMERIC(10,2) DEFAULT 0.00,
  animus_atque BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  adflicto_acer_774_id INTEGER REFERENCES adflicto_acer_774(id)
);
