-- Migration: create_table_suppono_possimus_arcus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE celer_bellicus_765 (
  id SERIAL PRIMARY KEY,
  uxor_repudiandae_cresco DATE DEFAULT CURRENT_DATE,
  ipsam_labore BOOLEAN,
  defendo_peccatus_vehemens MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr UNIQUE,
  cibo INT[] NOT NULL DEFAULT ARRAY[]::INT[],
  quod BYTEA NOT NULL,
  caput TIMESTAMP NOT NULL,
  ad_advoco JSON NOT NULL DEFAULT '{}'::json,
  cupiditas_tamen_culpo REAL NOT NULL,
  asperiores_barba REAL NOT NULL,
  deficio TIMESTAMPTZ UNIQUE,
  textus_cena NUMERIC(10,2) NOT NULL,
  tubineus_tempora TIMESTAMPTZ DEFAULT NOW() UNIQUE,
  admoneo_conduco BYTEA,
  suspendo BYTEA DEFAULT '\x00'::bytea,
  repudiandae_at_statua DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
