-- Migration: create_index_arbustum_calculus_quae
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_occaecati_dicta_611_derideo_coerceo_285_id ON occaecati_dicta_611 (derideo_coerceo_285_id);
