-- Migration: create_table_commemoro_casus_explicabo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE atque_vitium_693 (
  id SERIAL PRIMARY KEY,
  condico_canonicus JSONB,
  assentator_vociferor_accedo JSONB,
  cuppedia_synagoga REAL NOT NULL DEFAULT 0.0,
  corpus_depereo TIMESTAMPTZ DEFAULT NOW(),
  solvo_virga_suspendo VARCHAR(255) NOT NULL,
  voluptatibus_exercitationem INT[] DEFAULT ARRAY[]::INT[],
  totam_voveo DATE,
  deputo BYTEA NOT NULL,
  somnus_cumque_cicuta BYTEA DEFAULT '\x00'::bytea,
  quo INTEGER NOT NULL DEFAULT 0 UNIQUE,
  victoria MACADDR,
  corrumpo_stabilis_adversus DATE NOT NULL,
  succedo DOUBLE PRECISION UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  corpus_dicta_560_id INTEGER REFERENCES corpus_dicta_560(id)
);
