-- Migration: create_table_cotidie_tollo_votum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE spectaculum_tantum_791 (
  id SERIAL PRIMARY KEY,
  depulso VARCHAR(255),
  angelus_aranea BYTEA NOT NULL DEFAULT '\x00'::bytea UNIQUE,
  aequus_traho_suffoco VARCHAR(255),
  tonsor_vinitor TEXT[] NOT NULL UNIQUE,
  labore_curriculum_ventus INTEGER DEFAULT 0,
  angustus INTEGER NOT NULL,
  corrupti_circumvenio_ustilo SMALLINT NOT NULL DEFAULT 0,
  vallum JSON NOT NULL DEFAULT '{}'::json,
  eos_quo_subito UUID NOT NULL,
  cicuta INT[] NOT NULL,
  audeo UUID UNIQUE,
  vos_sublime_facilis TIMESTAMPTZ NOT NULL,
  traho_vir_surgo NUMERIC(10,2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  projects_id INTEGER REFERENCES projects(id)
);
