-- Migration: create_index_viscus_conicio_amiculum
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_paens_creator_969_compono_recusandae_delicate_cuppedia_cert ON paens_creator_969 (compono_recusandae, delicate_cuppedia_certus) WHERE compono_recusandae IS NOT NULL;
