-- Migration: create_view_clamo_ter_aestivus
-- Type: create_view
-- Generated by stress-generator

CREATE MATERIALIZED VIEW vw_cuppedia_alii_438 AS
SELECT a.id, a.eligendi_vel, a.patria_tollo_curtus, b.id, b.desolo_admoneo, b.voro_carbo
FROM demens_aliqua_626 a
CROSS JOIN derideo_coerceo_285 b
LIMIT 1000;
