-- Migration: create_index_praesentium_audentia_atrocitas
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_vinum_saepe_877_admiratio_cupressus ON vinum_saepe_877 (admiratio, cupressus) WHERE admiratio IS NOT NULL;
