-- Migration: create_index_aurum_tamdiu_antepono
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_aegrotatio_acies_136_vehemens_repellendus_depopulo_amo_infi ON aegrotatio_acies_136 (vehemens_repellendus, depopulo_amo_infit, tabella_tenus_absum);
