-- Migration: create_table_trepide_concido_certe
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE exercitationem_consuasor_792 (
  id SERIAL PRIMARY KEY,
  accedo_tolero_vigilo INET DEFAULT '0.0.0.0'::inet UNIQUE,
  quod_vos DATE,
  thymbra_curso_rem CIDR DEFAULT '0.0.0.0/0'::cidr,
  supellex INTEGER DEFAULT 0,
  sperno_adsidue INTEGER,
  vehemens REAL DEFAULT 0.0,
  cura_subvenio_temperantia INET UNIQUE,
  pax_balbus_verto INT[] NOT NULL,
  turbo CIDR DEFAULT '0.0.0.0/0'::cidr,
  ut TEXT,
  maiores_aetas_ascisco DATE,
  denuo VARCHAR(255) DEFAULT 'default',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
