-- Migration: alter_table_validus_supellex_aequus
-- Type: alter_table
-- Generated by stress-generator

ALTER TABLE spectaculum_tantum_791 ADD COLUMN perspiciatis VARCHAR(255) NOT NULL DEFAULT 'default';
