-- Migration: create_index_vulnero_dapifer_verumtamen
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_alo_atrox_797_thermae_sortitus_denuo ON alo_atrox_797 (thermae, sortitus_denuo);
