-- Migration: create_index_minima_solum_velociter
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_fuga_verto_346_tandem_conventus_nobis_ratione ON fuga_verto_346 (tandem, conventus_nobis_ratione) WHERE tandem IS NOT NULL;
