-- Migration: create_table_combibo_testimonium_vallum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE accedo_taceo_834 (
  id SERIAL PRIMARY KEY,
  tardus INET NOT NULL,
  alienus_depopulo VARCHAR(255) UNIQUE,
  amor_titulus INT[],
  aestus JSONB NOT NULL UNIQUE,
  culpa TIMESTAMPTZ DEFAULT NOW(),
  cultellus_ventus_comminor JSONB,
  contabesco_socius INTEGER NOT NULL,
  quibusdam_aequitas REAL,
  ipsam_eius_aranea INET,
  quo VARCHAR(255) NOT NULL UNIQUE,
  adipiscor_cetera REAL UNIQUE,
  talio TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
