-- Migration: create_index_dolorem_animadverto_color
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_demonstro_sonitus_936_patior_aliqua_vero ON demonstro_sonitus_936 (patior, aliqua_vero) WHERE patior IS NOT NULL;
