-- Migration: create_table_aperio_acerbitas_contra
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tener_nulla_782 (
  id SERIAL PRIMARY KEY,
  eaque_aqua_speciosus DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  tandem_ver_tempora NUMERIC(10,2) NOT NULL,
  aro_demitto BYTEA DEFAULT '\x00'::bytea,
  bestia DATE NOT NULL,
  subito DATE NOT NULL,
  stultus BOOLEAN NOT NULL,
  aufero REAL,
  tot_tergo BYTEA DEFAULT '\x00'::bytea,
  custodia_addo BOOLEAN,
  adficio_sopor TIMESTAMPTZ NOT NULL,
  vulnus_tremo_tutis BOOLEAN DEFAULT false UNIQUE,
  compello_tamisium_timidus MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
