-- Migration: create_index_ars_aeneus_absque
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_vulgivagus_aperte_796_cavus_ultio_urbanus_animus_amplitudo_ ON vulgivagus_aperte_796 (cavus_ultio_urbanus, animus_amplitudo_cunctatio, convoco_saepe);
