-- Migration: create_table_tempore_viriliter_adopto
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE canto_apto_612 (
  id SERIAL PRIMARY KEY,
  officia_coadunatio TEXT DEFAULT 'default_text',
  theca UUID,
  animus JSON,
  quam_illum BYTEA NOT NULL,
  custodia_cupiditate_tendo NUMERIC(10,2) UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
