-- Migration: create_index_desolo_cubitum_arca
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_stabilis_attonbitus_525_sunt_stultus_minima ON stabilis_attonbitus_525 (sunt_stultus, minima);
