-- Migration: trigger_function_provident_vomica_confero
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_odit_supplanto_241()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.blanditiis IS NULL THEN
    RAISE EXCEPTION 'blanditiis cannot be null on veniam_ulterius_668';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_veniam_ulterius_668_168
  BEFORE INSERT OR UPDATE ON veniam_ulterius_668
  FOR EACH ROW EXECUTE FUNCTION fn_odit_supplanto_241();
