-- Migration: trigger_function_cuius_terra_vivo
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_villa_theatrum_182()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_occaecati_vilicus_575_712
  BEFORE UPDATE ON occaecati_vilicus_575
  FOR EACH ROW EXECUTE FUNCTION fn_villa_theatrum_182();
