-- Migration: rls_policy_surgo_arto_subvenio
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE aequitas_temporibus_486 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_aequitas_temporibus_486_507" ON aequitas_temporibus_486 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_aequitas_temporibus_486_150" ON aequitas_temporibus_486 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_aequitas_temporibus_486_330" ON aequitas_temporibus_486 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_aequitas_temporibus_486_137" ON aequitas_temporibus_486 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
