-- Migration: create_table_cui_deinde_vinitor
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vigor_quisquam_335 (
  id SERIAL PRIMARY KEY,
  quam_expedita_varietas INET,
  ademptio_molestiae_tempus MACADDR,
  antiquus_crux_thema BIGINT,
  suasoria_illo BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
