-- Migration: create_index_audentia_deficio_tamisium
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_spectaculum_tantum_791_tonsor_vinitor ON spectaculum_tantum_791 (tonsor_vinitor);
