-- Migration: create_table_terreo_calcar_aurum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vel_congregatio_309 (
  id SERIAL PRIMARY KEY,
  admoveo TIMESTAMP NOT NULL,
  tabernus_velit UUID,
  abutor_comedo_termes REAL NOT NULL,
  decerno_vorago_modi SMALLINT,
  agnitio MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  comprehendo_utpote INTEGER DEFAULT 0,
  aedificium BYTEA,
  caelum_caput_necessitatibus JSON NOT NULL,
  validus_quasi TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  supplanto_inventore INET DEFAULT '0.0.0.0'::inet UNIQUE,
  sto_comparo NUMERIC(10,2) DEFAULT 0.00,
  speciosus_tripudio CIDR,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
