-- Migration: rls_policy_vehemens_ascisco_vulnero
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE tondeo_repellat_388 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_tondeo_repellat_388_537" ON tondeo_repellat_388 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_tondeo_repellat_388_771" ON tondeo_repellat_388 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_tondeo_repellat_388_661" ON tondeo_repellat_388 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_tondeo_repellat_388_409" ON tondeo_repellat_388 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
