-- Migration: create_table_ater_aeneus_cubo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE atque_teres_946 (
  id SERIAL PRIMARY KEY,
  vitium TEXT NOT NULL DEFAULT 'default_text',
  vigilo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  eveniet_vestrum_curto MACADDR,
  valde CIDR UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
