-- Migration: alter_table_amet_praesentium_ancilla
-- Type: alter_table
-- Generated by stress-generator

ALTER TABLE fuga_verto_346 ADD COLUMN contigo_canto_vicinus CIDR NOT NULL DEFAULT '0.0.0.0/0'::cidr;
