-- Migration: trigger_function_sufficio_sto_corrupti
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_curvo_comis_582()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on vaco_thymbra_505 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_vaco_thymbra_505_371
  AFTER INSERT OR UPDATE OR DELETE ON vaco_thymbra_505
  FOR EACH ROW EXECUTE FUNCTION fn_curvo_comis_582();
