-- Migration: create_index_venustas_adstringo_basium
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_eaque_utpote_741_bibo_qui_ait_aliquid_nesciunt ON eaque_utpote_741 (bibo_qui_ait, aliquid_nesciunt) WHERE bibo_qui_ait IS NOT NULL;
