-- Migration: create_table_at_caste_utpote
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE caecus_ademptio_503 (
  id SERIAL PRIMARY KEY,
  tandem SMALLINT NOT NULL,
  adfero_desidero_ultra NUMERIC(10,2),
  adhuc_aequitas_communis SMALLINT DEFAULT 0,
  victus BIGINT DEFAULT 0,
  testimonium_amicitia_tubineus DATE,
  validus_vestrum_capio DATE,
  comprehendo_corona_adflicto TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  bene_calculus_469_id INTEGER REFERENCES bene_calculus_469(id)
);
