-- Migration: create_view_bonus_theologus_benigne
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_vel_verumtamen_907 AS
SELECT a.id, a.textor_peccatus_depromo, a.cinis_occaecati_ocer, b.id, b.name, b.description
FROM consuasor_tametsi_551 a
CROSS JOIN projects b
LIMIT 1000;
