-- Migration: alter_table_spectaculum_adinventitias_bos
-- Type: alter_table
-- Generated by stress-generator

ALTER TABLE bellum_correptius_485 ADD COLUMN vis_combibo MACADDR DEFAULT '00:00:00:00:00:00'::macaddr;
