-- Migration: create_table_cognatus_vicissitudo_angustus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE soluta_exercitationem_104 (
  id SERIAL PRIMARY KEY,
  clibanus_vigilo CIDR NOT NULL DEFAULT '0.0.0.0/0'::cidr,
  conqueror_admitto VARCHAR(255) NOT NULL,
  casus_nesciunt TIMESTAMP NOT NULL,
  conventus_tibi TIMESTAMPTZ DEFAULT NOW(),
  turba_brevis DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
