-- Migration: alter_table_absconditus_distinctio_vulticulus
-- Type: alter_table
-- Generated by stress-generator

ALTER TABLE cervus_crur_422 ADD COLUMN triumphus NUMERIC(10,2) NOT NULL DEFAULT 0.00;
