-- Migration: create_table_amo_cultellus_thymum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tabernus_fugiat_216 (
  id SERIAL PRIMARY KEY,
  ubi_utrum_degero DOUBLE PRECISION DEFAULT 0.0,
  cito_ubi BIGINT DEFAULT 0,
  certe DATE,
  dolor_comedo CIDR,
  vomito_stultus_crapula BOOLEAN NOT NULL,
  compono_cum_ventus BYTEA NOT NULL,
  velut_ipsam BOOLEAN UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
