-- Migration: trigger_function_quia_degero_adflicto
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_tyrannus_paulatim_682()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_patrocinor_usitas_946_993
  BEFORE UPDATE ON patrocinor_usitas_946
  FOR EACH ROW EXECUTE FUNCTION fn_tyrannus_paulatim_682();
