-- Migration: create_table_quis_uterque_vorax
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE demonstro_sonitus_936 (
  id SERIAL PRIMARY KEY,
  addo BOOLEAN DEFAULT false,
  concido_tepidus INTEGER,
  dapifer_caritas_totus INET NOT NULL DEFAULT '0.0.0.0'::inet,
  aliqua_vero INTEGER NOT NULL,
  uterque_synagoga INET NOT NULL,
  deporto SMALLINT NOT NULL UNIQUE,
  vespillo_attollo_minus INT[],
  volup_vinco_demitto MACADDR NOT NULL,
  patior SMALLINT DEFAULT 0,
  surgo_aedificium TIMESTAMPTZ,
  valde_praesentium SMALLINT UNIQUE,
  eveniet_vigor_theologus TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
