-- Migration: rls_policy_abeo_spargo_sapiente
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE confugo_dolorem_615 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_confugo_dolorem_615_143" ON confugo_dolorem_615 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_confugo_dolorem_615_382" ON confugo_dolorem_615 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_confugo_dolorem_615_555" ON confugo_dolorem_615 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_confugo_dolorem_615_77" ON confugo_dolorem_615 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
