-- Migration: create_table_voluntarius_acer_thorax
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE sui_acer_419 (
  id SERIAL PRIMARY KEY,
  magni_bardus BYTEA,
  conservo_suppono_comis INT[] DEFAULT ARRAY[]::INT[],
  autus INT[] NOT NULL,
  centum_subvenio DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  amplitudo TEXT NOT NULL,
  coepi_argentum BOOLEAN,
  accusamus INTEGER,
  deleniti_conturbo_amitto MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  quibusdam_vindico NUMERIC(10,2) DEFAULT 0.00 UNIQUE,
  adduco BYTEA NOT NULL DEFAULT '\x00'::bytea,
  coerceo BOOLEAN DEFAULT false,
  vos_adsidue INTEGER UNIQUE,
  doloremque_et_libero BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  occaecati_vilicus_575_id INTEGER REFERENCES occaecati_vilicus_575(id)
);
