-- Migration: rls_policy_celebrer_adeptio_succurro
-- Type: rls_policy
-- Generated by stress-generator

CREATE POLICY "policy_select_absum_aequus_393_261" ON absum_aequus_393 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_absum_aequus_393_512" ON absum_aequus_393 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_absum_aequus_393_320" ON absum_aequus_393 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_absum_aequus_393_168" ON absum_aequus_393 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
