-- Migration: create_table_absens_comes_spiculum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE odio_desino_873 (
  id SERIAL PRIMARY KEY,
  sponte_sortitus_vilitas CIDR,
  defendo DATE UNIQUE,
  denego_quia_triduana TIMESTAMP,
  tricesimus_amitto_amitto DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
