-- Migration: create_table_addo_usus_aptus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE decens_tero_784 (
  id SERIAL PRIMARY KEY,
  tum_sollers_calco BOOLEAN DEFAULT false,
  deficio INT[],
  vesco JSON,
  adflicto_tumultus_dedico DOUBLE PRECISION,
  quae_defleo MACADDR,
  calculus_cultura CIDR,
  sapiente_cariosus INTEGER NOT NULL DEFAULT 0,
  conor_voluptate_volva BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  utique_voluntarius_177_id INTEGER REFERENCES utique_voluntarius_177(id)
);
