-- Migration: create_table_aro_repudiandae_uterque
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE accusantium_hic_956 (
  id SERIAL PRIMARY KEY,
  volo_suasoria BYTEA,
  subnecto_tabesco_clamo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  totidem INTEGER NOT NULL,
  cimentarius_commodo TIMESTAMP UNIQUE,
  correptius_sint TIMESTAMP NOT NULL,
  solum BOOLEAN,
  sufficio_colligo TIMESTAMPTZ,
  sufficio_fuga UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  demonstro_sonitus_936_id INTEGER REFERENCES demonstro_sonitus_936(id)
);
