-- Migration: create_table_tot_uter_voluptas
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE conservo_incidunt_533 (
  id SERIAL PRIMARY KEY,
  cetera_acceptus_aestus NUMERIC(10,2) DEFAULT 0.00,
  amoveo_combibo DATE UNIQUE,
  eius BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
