-- Migration: create_index_vomer_thymum_undique
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_decumbo_suscipio_693_commodi_causa_cervus_demitto ON decumbo_suscipio_693 USING gin (sint_defungo);
