-- Migration: create_view_cetera_brevis_et
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_cubicularis_agnosco_291 AS
SELECT a.id, a.vetus_verbum, a.quia_dens, b.id, b.vicinus, b.annus_caterva_torqueo
FROM aequitas_temporibus_486 a
CROSS JOIN bardus_statua_764 b
LIMIT 1000;
