-- Migration: create_index_viridis_textus_nihil
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_decretum_xiphias_835_centum_tamquam_vigilo_adnuo_sumo_amo ON decretum_xiphias_835 (centum, tamquam_vigilo_adnuo, sumo_amo);
