-- Migration: rls_policy_tero_viduo_stultus
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE coerceo_suggero_68 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_coerceo_suggero_68_136" ON coerceo_suggero_68 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_coerceo_suggero_68_146" ON coerceo_suggero_68 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_coerceo_suggero_68_697" ON coerceo_suggero_68 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_coerceo_suggero_68_643" ON coerceo_suggero_68 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
