-- Migration: rls_policy_vester_adversus_quisquam
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE vita_degenero_209 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_vita_degenero_209_267" ON vita_degenero_209 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_vita_degenero_209_268" ON vita_degenero_209 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_vita_degenero_209_889" ON vita_degenero_209 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_vita_degenero_209_772" ON vita_degenero_209 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
