-- Migration: create_table_cognatus_caveo_autem
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE curvo_aranea_890 (
  id SERIAL PRIMARY KEY,
  acies DOUBLE PRECISION NOT NULL UNIQUE,
  colo_spiculum NUMERIC(10,2) DEFAULT 0.00,
  sto_aqua JSONB,
  adficio_adaugeo DATE DEFAULT CURRENT_DATE,
  civitas_velut INTEGER NOT NULL,
  trepide_vorax TIMESTAMPTZ NOT NULL,
  hic_arguo JSON,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
