-- Migration: trigger_function_thalassinus_depraedor_adflicto
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_testimonium_attero_573()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_sollers_adflicto_598_983
  BEFORE UPDATE ON sollers_adflicto_598
  FOR EACH ROW EXECUTE FUNCTION fn_testimonium_attero_573();
