-- Migration: rls_policy_vomito_sed_sunt
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE sint_voluptatem_847 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_sint_voluptatem_847_64" ON sint_voluptatem_847 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_sint_voluptatem_847_387" ON sint_voluptatem_847 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_sint_voluptatem_847_283" ON sint_voluptatem_847 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_sint_voluptatem_847_305" ON sint_voluptatem_847 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
