-- Migration: create_table_curso_conculco_maxime
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE audio_sunt_353 (
  id SERIAL PRIMARY KEY,
  cultellus INTEGER DEFAULT 0,
  surculus_curatio DATE,
  taedium_tristis BYTEA UNIQUE,
  creber_apparatus_unus NUMERIC(10,2) DEFAULT 0.00,
  patior_volup_approbo JSON NOT NULL UNIQUE,
  perspiciatis_suscipit BYTEA NOT NULL,
  tergeo_viriliter VARCHAR(255),
  pecto_absque INET NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
