-- Migration: trigger_function_vere_turbo_ocer
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_claro_talis_506()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on labore_tendo_619 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_labore_tendo_619_162
  AFTER INSERT OR UPDATE OR DELETE ON labore_tendo_619
  FOR EACH ROW EXECUTE FUNCTION fn_claro_talis_506();
