-- Migration: create_index_decor_patria_clamo
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_canto_apto_612_animus_officia_coadunatio ON canto_apto_612 (animus, officia_coadunatio);
