-- Migration: create_table_considero_suasoria_vilis
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vita_degenero_209 (
  id SERIAL PRIMARY KEY,
  cenaculum MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  annus_demens DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  spiculum UUID,
  contabesco DOUBLE PRECISION DEFAULT 0.0 UNIQUE,
  curto_canis VARCHAR(255),
  absque_voco_congregatio TEXT[],
  turbo_tamen TEXT[] NOT NULL UNIQUE,
  ipsa_subseco_cum JSON NOT NULL DEFAULT '{}'::json,
  textor VARCHAR(255) DEFAULT 'default',
  adinventitias_vita TEXT[],
  cedo JSONB DEFAULT '{}'::jsonb,
  sollers_auditor JSON,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
