-- Migration: trigger_function_valens_voluptates_labore
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_demum_amet_785()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_canis_dolorum_322_697
  BEFORE UPDATE ON canis_dolorum_322
  FOR EACH ROW EXECUTE FUNCTION fn_demum_amet_785();
