-- Migration: trigger_function_curo_vomito_aro
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_calculus_amita_140()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_absum_aequus_393_513
  BEFORE UPDATE ON absum_aequus_393
  FOR EACH ROW EXECUTE FUNCTION fn_calculus_amita_140();
