-- Migration: create_table_clibanus_coepi_talus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vaco_thymbra_505 (
  id SERIAL PRIMARY KEY,
  vorax_sordeo DOUBLE PRECISION,
  abundans JSON,
  suus BIGINT NOT NULL,
  comburo_deludo_trado UUID,
  atavus_summa CIDR DEFAULT '0.0.0.0/0'::cidr,
  defaeco_tamquam DOUBLE PRECISION NOT NULL,
  volva_reiciendis INTEGER NOT NULL,
  ater CIDR,
  suasoria_dolores TIMESTAMPTZ DEFAULT NOW(),
  vigilo_ut INET NOT NULL,
  speciosus_laborum_amor UUID,
  voluptatibus_amor DATE,
  una TIMESTAMPTZ NOT NULL,
  vivo BYTEA,
  amplexus_succedo_hic INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  absum_aequus_393_id INTEGER REFERENCES absum_aequus_393(id)
);
