-- Migration: create_table_crapula_tempus_error
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE desparatus_armarium_128 (
  id SERIAL PRIMARY KEY,
  contego_amiculum TIMESTAMPTZ,
  tunc_socius REAL NOT NULL,
  tripudio_odit_somniculosus DOUBLE PRECISION DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
