-- Migration: create_table_demens_calcar_aspernatur
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE coepi_demitto_168 (
  id SERIAL PRIMARY KEY,
  adsuesco_nostrum MACADDR,
  substantia_cunctatio JSONB,
  corona TEXT[],
  non_theologus_urbs UUID,
  agnosco_urbanus_denique VARCHAR(255),
  trepide JSON,
  delicate MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  thesaurus_ipsum_397_id INTEGER REFERENCES thesaurus_ipsum_397(id)
);
