-- Migration: create_table_capto_vicissitudo_vomica
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE aeternus_acidus_252 (
  id SERIAL PRIMARY KEY,
  terebro_sumptus NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  cui_cultellus INTEGER NOT NULL DEFAULT 0,
  aestas BIGINT DEFAULT 0,
  anser_sint TEXT[] DEFAULT ARRAY[]::TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  adhaero_averto_179_id INTEGER REFERENCES adhaero_averto_179(id)
);
