-- Migration: create_table_crudelis_tyrannus_curso
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE infit_arbor_134 (
  id SERIAL PRIMARY KEY,
  attollo_cum_constans INET DEFAULT '0.0.0.0'::inet,
  celebrer_coruscus JSONB DEFAULT '{}'::jsonb,
  ter BIGINT,
  depulso_basium_tabula REAL,
  undique_sto_vigilo BYTEA UNIQUE,
  talio_crepusculum TIMESTAMPTZ UNIQUE,
  articulus_sub INTEGER NOT NULL DEFAULT 0,
  accusamus_debitis_acer JSONB,
  spectaculum_tero JSON DEFAULT '{}'::json,
  carus SMALLINT,
  sapiente CIDR DEFAULT '0.0.0.0/0'::cidr,
  cohaero BYTEA DEFAULT '\x00'::bytea,
  deficio_sublime_cresco BIGINT,
  dignissimos TIMESTAMPTZ DEFAULT NOW(),
  iste_defendo_circumvenio TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
