-- Migration: create_view_despecto_supellex_unus
-- Type: create_view
-- Generated by stress-generator

CREATE MATERIALIZED VIEW vw_totidem_in_967 AS
SELECT a.id, a.minima, a.adimpleo_recusandae, b.id, b.depulso, b.angelus_aranea
FROM stabilis_attonbitus_525 a
CROSS JOIN spectaculum_tantum_791 b
LIMIT 1000;
