-- Migration: trigger_function_cogito_uberrime_tempore
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_soluta_cum_262()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on curiositas_denique_376 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_curiositas_denique_376_979
  AFTER INSERT OR UPDATE OR DELETE ON curiositas_denique_376
  FOR EACH ROW EXECUTE FUNCTION fn_soluta_cum_262();
