-- Migration: create_table_terror_concido_tripudio
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE thesaurus_denuo_574 (
  id SERIAL PRIMARY KEY,
  cunae INET NOT NULL DEFAULT '0.0.0.0'::inet,
  voveo INT[],
  subseco_vitae_patior DOUBLE PRECISION NOT NULL,
  correptius BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
