-- Migration: create_table_temporibus_arma_depono
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE corrupti_thema_368 (
  id SERIAL PRIMARY KEY,
  tutis_theca BIGINT NOT NULL DEFAULT 0,
  carus_celebrer_a MACADDR NOT NULL,
  defungo TIMESTAMP,
  claro SMALLINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
