-- Migration: rls_policy_patior_tactus_bene
-- Type: rls_policy
-- Generated by stress-generator

CREATE POLICY "policy_select_sint_voluptatem_847_607" ON sint_voluptatem_847 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_sint_voluptatem_847_89" ON sint_voluptatem_847 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_sint_voluptatem_847_677" ON sint_voluptatem_847 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_sint_voluptatem_847_65" ON sint_voluptatem_847 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
