-- Migration: rls_policy_fugiat_tunc_vox
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE solutio_tendo_265 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_solutio_tendo_265_667" ON solutio_tendo_265 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_solutio_tendo_265_777" ON solutio_tendo_265 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_solutio_tendo_265_862" ON solutio_tendo_265 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_solutio_tendo_265_314" ON solutio_tendo_265 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
