-- Migration: create_table_desolo_teneo_deorsum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE utroque_vociferor_342 (
  id SERIAL PRIMARY KEY,
  sponte CIDR DEFAULT '0.0.0.0/0'::cidr,
  adinventitias_quasi TIMESTAMPTZ,
  vinitor_cum INET,
  video CIDR NOT NULL DEFAULT '0.0.0.0/0'::cidr,
  civitas_viridis_admiratio BIGINT,
  vitium TEXT DEFAULT 'default_text',
  sophismata_traho_abutor JSON UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
