-- Migration: rls_policy_ara_delibero_consuasor
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE canto_apto_612 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_canto_apto_612_92" ON canto_apto_612 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_canto_apto_612_114" ON canto_apto_612 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_canto_apto_612_109" ON canto_apto_612 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_canto_apto_612_724" ON canto_apto_612 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
