-- Migration: create_index_tantum_alius_commemoro
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_vulgivagus_aperte_796_cavus_ultio_urbanus_utroque_animus_am ON vulgivagus_aperte_796 (cavus_ultio_urbanus, utroque, animus_amplitudo_cunctatio);
