-- Migration: create_table_commodi_tollo_caterva
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE bellum_correptius_485 (
  id SERIAL PRIMARY KEY,
  delectatio_tametsi TEXT,
  exercitationem_amita UUID DEFAULT gen_random_uuid(),
  accusator_comminor SMALLINT DEFAULT 0,
  spoliatio_testimonium JSONB,
  custodia_antiquus_ciminatio TIMESTAMP NOT NULL,
  pecto_capillus_ambitus BIGINT DEFAULT 0,
  atavus MACADDR,
  amoveo_cubicularis_volubilis MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  vetus_iusto_mollitia BOOLEAN NOT NULL DEFAULT false,
  distinctio_carcer INTEGER NOT NULL DEFAULT 0,
  denique JSON,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  paens_creator_969_id INTEGER REFERENCES paens_creator_969(id)
);
