-- Migration: create_index_pecto_temeritas_venia
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_occaecati_dicta_611_tumultus_ante_verumtamen ON occaecati_dicta_611 (tumultus_ante_verumtamen);
