-- Migration: trigger_function_absconditus_suffragium_viduo
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_vitae_terebro_906()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_ambulo_aetas_593_235
  BEFORE UPDATE ON ambulo_aetas_593
  FOR EACH ROW EXECUTE FUNCTION fn_vitae_terebro_906();
