-- Migration: create_table_ratione_dedico_clarus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE occaecati_vilicus_575 (
  id SERIAL PRIMARY KEY,
  defungo_in INT[],
  aegrus INTEGER DEFAULT 0,
  comis CIDR,
  subiungo DOUBLE PRECISION NOT NULL,
  atrocitas BYTEA NOT NULL,
  tergeo_confugo INT[] NOT NULL,
  amet_veniam_despecto CIDR,
  ventosus VARCHAR(255),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
