-- Migration: create_view_tubineus_virga_tibi
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_aperte_bestia_656 AS
SELECT a.id, a.somniculosus, a.terga_vigor_varius, b.id, b.minima, b.adimpleo_recusandae
FROM animus_deputo_35 a
CROSS JOIN stabilis_attonbitus_525 b
LIMIT 1000;
