-- Migration: create_table_vulariter_templum_tui
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE artificiose_solum_870 (
  id SERIAL PRIMARY KEY,
  esse_conatus TEXT[],
  cruentus_vobis NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  tamdiu_ventosus_abeo TEXT DEFAULT 'default_text',
  demergo VARCHAR(255) UNIQUE,
  cruciamentum_vox SMALLINT,
  volo_depraedor_subito INTEGER,
  tamen_catena_utique UUID,
  infit_creber_tollo NUMERIC(10,2) DEFAULT 0.00,
  urbanus TIMESTAMP NOT NULL,
  tendo_templum JSON NOT NULL,
  considero_vulnus_dapifer TEXT DEFAULT 'default_text',
  adnuo REAL DEFAULT 0.0 UNIQUE,
  ceno NUMERIC(10,2) NOT NULL,
  celo VARCHAR(255) NOT NULL DEFAULT 'default',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  nisi_laudantium_561_id INTEGER REFERENCES nisi_laudantium_561(id)
);
