-- Migration: create_table_alveus_curatio_torrens
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE ambulo_aetas_593 (
  id SERIAL PRIMARY KEY,
  unus_curriculum INT[],
  alii DOUBLE PRECISION,
  patior_desino TEXT[] NOT NULL,
  cena_bellicus_vinco TEXT NOT NULL DEFAULT 'default_text',
  consequatur SMALLINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  occaecati_vilicus_575_id INTEGER REFERENCES occaecati_vilicus_575(id)
);
