-- Migration: rls_policy_sequi_administratio_contigo
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE conicio_centum_966 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_conicio_centum_966_702" ON conicio_centum_966 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_conicio_centum_966_298" ON conicio_centum_966 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_conicio_centum_966_106" ON conicio_centum_966 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_conicio_centum_966_782" ON conicio_centum_966 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
