-- Migration: create_table_constans_caste_suasoria
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE voluptate_argumentum_270 (
  id SERIAL PRIMARY KEY,
  arguo_textus INET DEFAULT '0.0.0.0'::inet,
  sublime_agnitio_cura JSON,
  terminatio CIDR,
  argumentum_agnitio_sapiente UUID NOT NULL,
  defleo_conitor REAL NOT NULL,
  sumptus DATE NOT NULL,
  viridis_truculenter_veniam CIDR DEFAULT '0.0.0.0/0'::cidr,
  error JSONB,
  corporis DATE,
  ultio_timidus INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  tener_nulla_782_id INTEGER REFERENCES tener_nulla_782(id)
);
