-- Migration: create_table_mollitia_venustas_annus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE consuasor_tametsi_551 (
  id SERIAL PRIMARY KEY,
  textor_peccatus_depromo TEXT NOT NULL,
  cinis_occaecati_ocer UUID NOT NULL DEFAULT gen_random_uuid(),
  somnus_terreo DATE NOT NULL DEFAULT CURRENT_DATE,
  suspendo_accusator SMALLINT,
  denuo_depraedor_animadverto INET,
  eius_spiculum_tergo INTEGER NOT NULL DEFAULT 0,
  auctor TIMESTAMP UNIQUE,
  auctor_natus DOUBLE PRECISION,
  damnatio_denuo_socius TEXT NOT NULL,
  alioqui INT[] NOT NULL DEFAULT ARRAY[]::INT[],
  truculenter_adimpleo SMALLINT NOT NULL DEFAULT 0,
  placeat_cedo_aeger TEXT,
  versus_cumque_aureus JSONB NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
