-- Migration: create_index_clibanus_arbitro_argentum
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_spectaculum_tantum_791_cicuta_aequus_traho_suffoco ON spectaculum_tantum_791 (cicuta, aequus_traho_suffoco);
