-- Migration: create_table_ascisco_aeneus_sapiente
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE eaque_utpote_741 (
  id SERIAL PRIMARY KEY,
  contigo_claudeo_tolero CIDR NOT NULL,
  theologus_sol REAL NOT NULL,
  aliquid_nesciunt TEXT,
  adaugeo_adfero CIDR DEFAULT '0.0.0.0/0'::cidr,
  bibo_qui_ait VARCHAR(255),
  voluptates_ducimus_commodi INET UNIQUE,
  vivo CIDR NOT NULL,
  carus JSON NOT NULL,
  taceo_iste_perspiciatis DATE,
  ancilla TEXT,
  alter_deprimo UUID,
  rem_adipisci TIMESTAMP NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
