-- Migration: create_table_tertius_caute_suggero
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE sulum_spiculum_25 (
  id SERIAL PRIMARY KEY,
  sortitus SMALLINT,
  volutabrum_abstergo_qui DATE NOT NULL DEFAULT CURRENT_DATE,
  textus_ait BIGINT NOT NULL DEFAULT 0,
  solum TIMESTAMP NOT NULL,
  aegrus NUMERIC(10,2),
  cubicularis_acquiro TIMESTAMP NOT NULL,
  uberrime_decet TEXT,
  aeneus_auditor_tepidus CIDR NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
