-- Migration: trigger_function_umerus_eos_conventus
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_clarus_ipsa_319()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_illum_abscido_325_424
  BEFORE UPDATE ON illum_abscido_325
  FOR EACH ROW EXECUTE FUNCTION fn_clarus_ipsa_319();
