-- Migration: create_view_somnus_congregatio_stella
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_unde_cattus_380 AS
SELECT a.id, a.cultura, a.tolero_virga, b.id, b.confero, b.tubineus_bibo
FROM utique_voluntarius_177 a
CROSS JOIN thema_suppellex_87 b
LIMIT 1000;
