-- Migration: create_index_casus_cruciamentum_sint
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_curiositas_denique_376_conculco_beatus_caput ON curiositas_denique_376 (conculco_beatus, caput) WHERE conculco_beatus IS NOT NULL;
