-- Migration: create_table_vis_cupio_viridis
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tam_summa_59 (
  id SERIAL PRIMARY KEY,
  venio INT[] NOT NULL,
  molestiae_cohaero_blandior TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  candidus_odit INT[] NOT NULL,
  audentia_varius BOOLEAN,
  ad_approbo BIGINT,
  utilis_benigne TIMESTAMPTZ,
  temptatio_in DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  perferendis_atrox_coruscus UUID DEFAULT gen_random_uuid(),
  denique_sponte_velit INTEGER,
  vorax UUID DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
