-- Migration: rls_policy_succurro_statua_crudelis
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE clarus_spoliatio_316 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_clarus_spoliatio_316_260" ON clarus_spoliatio_316 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_clarus_spoliatio_316_301" ON clarus_spoliatio_316 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_clarus_spoliatio_316_661" ON clarus_spoliatio_316 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_clarus_spoliatio_316_695" ON clarus_spoliatio_316 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
