-- Migration: rls_policy_combibo_deinde_cribro
-- Type: rls_policy
-- Generated by stress-generator

CREATE POLICY "policy_select_confugo_dolorem_615_643" ON confugo_dolorem_615 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_confugo_dolorem_615_88" ON confugo_dolorem_615 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_confugo_dolorem_615_893" ON confugo_dolorem_615 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_confugo_dolorem_615_389" ON confugo_dolorem_615 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
