-- Migration: create_table_cohaero_crux_dedecor
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE strues_averto_536 (
  id SERIAL PRIMARY KEY,
  temperantia_conqueror DOUBLE PRECISION NOT NULL,
  argumentum_vulgivagus INT[],
  alii_temeritas INTEGER NOT NULL,
  cognatus BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
