-- Migration: trigger_function_conqueror_corrigo_ab
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_cena_accommodo_294()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on calamitas_similique_175 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_calamitas_similique_175_773
  AFTER INSERT OR UPDATE OR DELETE ON calamitas_similique_175
  FOR EACH ROW EXECUTE FUNCTION fn_cena_accommodo_294();
