-- Migration: create_index_nulla_arca_clibanus
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_celer_bellicus_765_admoneo_conduco_quod_ipsam_labore ON celer_bellicus_765 (admoneo_conduco, quod, ipsam_labore) WHERE admoneo_conduco IS NOT NULL;
