-- Migration: create_index_ventus_venia_voluptatibus
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_adfero_annus_986_averto_adstringo ON adfero_annus_986 (averto, adstringo);
