-- Migration: create_table_aduro_charisma_timidus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE paens_creator_969 (
  id SERIAL PRIMARY KEY,
  delicate_cuppedia_certus VARCHAR(255) NOT NULL,
  itaque_tenus_vinco CIDR,
  pecto_calco_spectaculum NUMERIC(10,2) DEFAULT 0.00,
  ter_eius CIDR,
  appello_ad BYTEA NOT NULL,
  accedo TIMESTAMP,
  conqueror_doloribus_terra DATE NOT NULL,
  vester JSONB,
  compono_recusandae BOOLEAN DEFAULT false,
  aptus DOUBLE PRECISION,
  sopor_at SMALLINT DEFAULT 0,
  alienus INTEGER DEFAULT 0,
  strues_adflicto INET NOT NULL DEFAULT '0.0.0.0'::inet,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
