-- Migration: create_table_thymbra_abeo_concido
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE occaecati_dicta_611 (
  id SERIAL PRIMARY KEY,
  vicissitudo_maiores_subito INT[] NOT NULL DEFAULT ARRAY[]::INT[],
  curriculum_tabgo INT[] NOT NULL,
  tumultus_ante_verumtamen MACADDR,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  derideo_coerceo_285_id INTEGER REFERENCES derideo_coerceo_285(id)
);
