-- Migration: create_table_barba_itaque_tabella
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE confero_vestrum_225 (
  id SERIAL PRIMARY KEY,
  decens_placeat INT[] DEFAULT ARRAY[]::INT[],
  sint_circumvenio_totam MACADDR NOT NULL,
  degusto_turbo_suscipit INET NOT NULL DEFAULT '0.0.0.0'::inet,
  viduo_adimpleo_asper INTEGER NOT NULL,
  tunc_tabella JSON,
  strenuus_uterque DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  caritas BYTEA NOT NULL DEFAULT '\x00'::bytea,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
