-- Migration: rls_policy_triduana_vociferor_ante
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE eaque_utpote_741 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_eaque_utpote_741_472" ON eaque_utpote_741 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_eaque_utpote_741_412" ON eaque_utpote_741 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_eaque_utpote_741_349" ON eaque_utpote_741 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_eaque_utpote_741_929" ON eaque_utpote_741 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
