-- Migration: create_index_vitae_carmen_conqueror
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_sint_voluptatem_847_territo_vulgaris_illum_denuo ON sint_voluptatem_847 (territo_vulgaris_illum, denuo) WHERE territo_vulgaris_illum IS NOT NULL;
