-- Migration: create_table_suadeo_bardus_adsum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE bos_sono_895 (
  id SERIAL PRIMARY KEY,
  conturbo_taceo BYTEA NOT NULL DEFAULT '\x00'::bytea,
  texo_bestia TIMESTAMP NOT NULL DEFAULT NOW(),
  tantillus_cilicium SMALLINT NOT NULL,
  vulticulus SMALLINT NOT NULL,
  patria_abstergo_utroque UUID NOT NULL,
  tamdiu TIMESTAMP DEFAULT NOW(),
  complectus MACADDR UNIQUE,
  dens_voluptatum CIDR,
  aestas_conqueror SMALLINT NOT NULL,
  aiunt_tabesco CIDR NOT NULL,
  armarium_asper_aeneus TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
