-- Migration: create_index_vobis_utroque_sequi
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_adaugeo_causa_463_tricesimus_curvo_baiulus_speculum_volubil ON adaugeo_causa_463 (tricesimus_curvo, baiulus_speculum_volubilis, apostolus_sumptus_verbera);
