-- Migration: create_table_cur_voluptas_tabgo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE conturbo_temperantia_369 (
  id SERIAL PRIMARY KEY,
  curo_magni INT[] DEFAULT ARRAY[]::INT[],
  vox_denuo_delibero DOUBLE PRECISION,
  derideo_deinde_repudiandae UUID DEFAULT gen_random_uuid(),
  traho_cibo JSONB DEFAULT '{}'::jsonb,
  aeternus_suppellex_conqueror TEXT[] DEFAULT ARRAY[]::TEXT[],
  aurum_sui_aduro INT[],
  voluptate_vulariter DOUBLE PRECISION,
  modi_accusamus REAL NOT NULL DEFAULT 0.0,
  statim_ait DOUBLE PRECISION,
  angustus_officiis_volubilis BIGINT NOT NULL,
  civis INT[] DEFAULT ARRAY[]::INT[],
  theca DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  celer_bellicus_765_id INTEGER REFERENCES celer_bellicus_765(id)
);
