-- Migration: create_table_arx_corrigo_uberrime
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE labore_tendo_619 (
  id SERIAL PRIMARY KEY,
  templum TEXT[] NOT NULL,
  esse_demoror UUID NOT NULL,
  adfero NUMERIC(10,2) DEFAULT 0.00,
  tantum_desparatus_varius INT[] NOT NULL,
  certus_balbus_decimus VARCHAR(255) NOT NULL,
  derideo_adduco NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  absum_aequus_393_id INTEGER REFERENCES absum_aequus_393(id)
);
