-- Migration: trigger_function_cursim_aperte_subnecto
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_tabula_aperiam_512()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_demens_aliqua_626_279
  BEFORE UPDATE ON demens_aliqua_626
  FOR EACH ROW EXECUTE FUNCTION fn_tabula_aperiam_512();
