-- Migration: create_table_acerbitas_decor_terminatio
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE thymbra_vulnero_253 (
  id SERIAL PRIMARY KEY,
  claustrum_accendo SMALLINT,
  sufficio_ait_sol DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  vicissitudo_suppellex_teneo VARCHAR(255) DEFAULT 'default',
  appono_delicate_vigilo BIGINT NOT NULL,
  comedo DATE DEFAULT CURRENT_DATE,
  tabella TEXT,
  solio REAL NOT NULL,
  vesica_defluo_tyrannus UUID DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
