-- Migration: create_table_molestiae_ventus_terreo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE animadverto_sodalitas_567 (
  id SERIAL PRIMARY KEY,
  delicate INT[],
  earum_una_crinis MACADDR DEFAULT '00:00:00:00:00:00'::macaddr UNIQUE,
  cur_calco_campana MACADDR NOT NULL,
  cruciamentum_veritas INTEGER,
  earum_apud JSONB DEFAULT '{}'::jsonb UNIQUE,
  cursus_quis_suscipio REAL,
  deputo_ulciscor MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  accusamus MACADDR,
  baiulus_canis_eligendi BIGINT,
  tertius BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  bellum_correptius_485_id INTEGER REFERENCES bellum_correptius_485(id)
);
