-- Migration: create_index_suadeo_vulariter_chirographum
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_animus_deputo_35_ancilla_urbanus_temptatio_laudantium_tepid ON animus_deputo_35 USING gin (temptatio_laudantium_tepidus);
