-- Migration: trigger_function_sollicito_asperiores_dapifer
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_culpo_carcer_890()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_corrupti_thema_368_914
  BEFORE UPDATE ON corrupti_thema_368
  FOR EACH ROW EXECUTE FUNCTION fn_culpo_carcer_890();
