-- Migration: create_index_vix_earum_spiculum
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_canis_adicio_18_harum_termes_vacuus_vestigium_vulgus ON canis_adicio_18 (harum_termes, vacuus_vestigium_vulgus);
