-- Migration: create_table_vicissitudo_ambulo_viduo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE canis_adicio_18 (
  id SERIAL PRIMARY KEY,
  credo_spoliatio SMALLINT NOT NULL UNIQUE,
  utroque_vinco UUID NOT NULL DEFAULT gen_random_uuid(),
  vilitas DOUBLE PRECISION NOT NULL,
  bos BIGINT NOT NULL UNIQUE,
  vacuus_vestigium_vulgus BIGINT,
  totam SMALLINT,
  aliqua_utpote BOOLEAN,
  tolero_sollers_ipsa VARCHAR(255),
  derelinquo_aggero_bonus REAL,
  omnis_tredecim TIMESTAMP NOT NULL,
  thema_solus_ullam MACADDR NOT NULL,
  quae_tantum_articulus MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  conculco BYTEA,
  absconditus_cito NUMERIC(10,2) NOT NULL,
  harum_termes INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  bellum_correptius_485_id INTEGER REFERENCES bellum_correptius_485(id)
);
