-- Migration: create_table_veritas_temperantia_traho
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE ducimus_textus_433 (
  id SERIAL PRIMARY KEY,
  currus_peccatus_adopto CIDR NOT NULL UNIQUE,
  abundans_ab NUMERIC(10,2) DEFAULT 0.00,
  combibo BIGINT,
  alii VARCHAR(255),
  amaritudo NUMERIC(10,2) NOT NULL,
  appono_clam DOUBLE PRECISION NOT NULL,
  uxor_occaecati INET,
  tergum_surgo VARCHAR(255) DEFAULT 'default',
  amo_animus_paens TIMESTAMP,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  audax_antea_139_id INTEGER REFERENCES audax_antea_139(id)
);
