-- Migration: rls_policy_cras_turpis_sequi
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE stabilis_attonbitus_525 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_stabilis_attonbitus_525_578" ON stabilis_attonbitus_525 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_stabilis_attonbitus_525_911" ON stabilis_attonbitus_525 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_stabilis_attonbitus_525_554" ON stabilis_attonbitus_525 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_stabilis_attonbitus_525_175" ON stabilis_attonbitus_525 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
