-- Migration: rls_policy_aptus_uxor_tamquam
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE utrum_amaritudo_141 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_utrum_amaritudo_141_780" ON utrum_amaritudo_141 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_utrum_amaritudo_141_644" ON utrum_amaritudo_141 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_utrum_amaritudo_141_117" ON utrum_amaritudo_141 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_utrum_amaritudo_141_374" ON utrum_amaritudo_141 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
