-- Migration: rls_policy_amplitudo_tricesimus_temptatio
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE vulnus_tantillus_645 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_vulnus_tantillus_645_136" ON vulnus_tantillus_645 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_vulnus_tantillus_645_315" ON vulnus_tantillus_645 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_vulnus_tantillus_645_320" ON vulnus_tantillus_645 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_vulnus_tantillus_645_700" ON vulnus_tantillus_645 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
