-- Migration: create_table_aliquam_odio_denique
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE constans_terreo_554 (
  id SERIAL PRIMARY KEY,
  adeptio_tamdiu_balbus TEXT[],
  utor TEXT[],
  optio_cruciamentum_cupiditate REAL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
