-- Migration: create_table_sufficio_bardus_varius
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE aliquam_summa_70 (
  id SERIAL PRIMARY KEY,
  colo_usus BIGINT UNIQUE,
  totam_vicissitudo_utor TIMESTAMPTZ DEFAULT NOW(),
  comburo MACADDR,
  volubilis_clementia DOUBLE PRECISION DEFAULT 0.0,
  altus_aegrus_arguo INET NOT NULL,
  tener_tonsor_torqueo DOUBLE PRECISION,
  admoneo TEXT[],
  aggero BIGINT,
  decimus_eaque_enim JSON DEFAULT '{}'::json UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  vigor_quisquam_335_id INTEGER REFERENCES vigor_quisquam_335(id)
);
