-- Migration: rls_policy_quis_comminor_caritas
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE illum_abscido_325 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_illum_abscido_325_50" ON illum_abscido_325 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_illum_abscido_325_848" ON illum_abscido_325 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_illum_abscido_325_10" ON illum_abscido_325 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_illum_abscido_325_937" ON illum_abscido_325 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
