-- Migration: create_view_culpo_cruentus_cognatus
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_cilicium_infit_84 AS
SELECT a.id, a.tum_sollers_calco, a.deficio, b.id, b.utrum_cupiditate, b.animus_amplitudo_cunctatio
FROM decens_tero_784 a
CROSS JOIN vulgivagus_aperte_796 b
LIMIT 1000;
