-- Migration: create_table_adulescens_libero_vita
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE stabilis_attonbitus_525 (
  id SERIAL PRIMARY KEY,
  minima BOOLEAN NOT NULL,
  adimpleo_recusandae INT[] NOT NULL,
  beneficium NUMERIC(10,2),
  capillus_termes BOOLEAN NOT NULL,
  quia UUID DEFAULT gen_random_uuid(),
  bis_allatus_acervus DOUBLE PRECISION NOT NULL,
  paens_derideo TEXT[],
  sunt_stultus TEXT[] DEFAULT ARRAY[]::TEXT[],
  certus_ager VARCHAR(255) NOT NULL DEFAULT 'default',
  conspergo VARCHAR(255) DEFAULT 'default',
  harum MACADDR NOT NULL,
  sortitus TEXT[] NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
