-- Migration: create_view_collum_baiulus_ver
-- Type: create_view
-- Generated by stress-generator

CREATE MATERIALIZED VIEW vw_sodalitas_velum_623 AS
SELECT a.id, a.name, a.description, b.id, b.ocer_nobis_vulariter, b.patria
FROM projects a
CROSS JOIN tui_quaerat_563 b
LIMIT 1000;
