-- Migration: create_view_apto_officiis_comburo
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_sublime_cauda_564 AS
SELECT a.id, a.clibanus_vigilo, a.conqueror_admitto, b.id, b.credo_spoliatio, b.utroque_vinco
FROM soluta_exercitationem_104 a
CROSS JOIN canis_adicio_18 b
LIMIT 1000;
