-- Migration: create_table_solium_spectaculum_abscido
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE decretum_xiphias_835 (
  id SERIAL PRIMARY KEY,
  ambulo_calcar_abduco TIMESTAMPTZ,
  tamquam_vigilo_adnuo TEXT NOT NULL DEFAULT 'default_text',
  centum JSONB,
  caste_aspernatur TIMESTAMP NOT NULL,
  odio JSON,
  sumo_amo BYTEA DEFAULT '\x00'::bytea,
  adulescens_decipio_audentia JSONB NOT NULL,
  pax_color INT[] NOT NULL,
  ademptio CIDR,
  ante_umquam_velit INT[] DEFAULT ARRAY[]::INT[],
  atque NUMERIC(10,2) UNIQUE,
  tenax_tempore MACADDR NOT NULL,
  accedo_absconditus BOOLEAN DEFAULT false,
  verbera TEXT NOT NULL DEFAULT 'default_text',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
