-- Migration: trigger_function_vigilo_ait_creptio
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_conculco_aeger_975()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.id IS NULL THEN
    RAISE EXCEPTION 'id cannot be null on animus_deputo_35';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_animus_deputo_35_817
  BEFORE INSERT OR UPDATE ON animus_deputo_35
  FOR EACH ROW EXECUTE FUNCTION fn_conculco_aeger_975();
