-- Migration: create_view_tripudio_tenetur_consequatur
-- Type: create_view
-- Generated by stress-generator

CREATE MATERIALIZED VIEW vw_coniuratio_quas_39 AS
SELECT a.id, a.minima, a.adimpleo_recusandae, b.id, b.vicissitudo_maiores_subito, b.curriculum_tabgo
FROM stabilis_attonbitus_525 a
CROSS JOIN occaecati_dicta_611 b
LIMIT 1000;
