-- Migration: create_table_venustas_aspicio_absque
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE annus_depulso_277 (
  id SERIAL PRIMARY KEY,
  dapifer_amoveo INTEGER NOT NULL,
  adnuo NUMERIC(10,2) NOT NULL,
  videlicet_advoco_aurum VARCHAR(255) NOT NULL,
  certus TIMESTAMPTZ DEFAULT NOW() UNIQUE,
  coaegresco_defero_antiquus INET,
  vallum_nemo_victoria TIMESTAMPTZ DEFAULT NOW(),
  terebro_architecto_decor BIGINT NOT NULL DEFAULT 0,
  claro CIDR DEFAULT '0.0.0.0/0'::cidr,
  voro NUMERIC(10,2) UNIQUE,
  vespillo_utilis_congregatio TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
