-- Migration: create_view_adstringo_tener_subvenio
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_contego_vere_21 AS
SELECT a.id, a.acies, a.colo_spiculum, b.id, b.name, b.description
FROM curvo_aranea_890 a
CROSS JOIN projects b
LIMIT 1000;
