-- Migration: rls_policy_caelum_provident_adhaero
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE curvo_aranea_890 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_curvo_aranea_890_301" ON curvo_aranea_890 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_curvo_aranea_890_184" ON curvo_aranea_890 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_curvo_aranea_890_756" ON curvo_aranea_890 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_curvo_aranea_890_474" ON curvo_aranea_890 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
