-- Migration: create_table_talus_admitto_bos
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tabesco_depono_813 (
  id SERIAL PRIMARY KEY,
  verbera_doloremque_contigo UUID NOT NULL,
  tot_volutabrum_utrum BOOLEAN DEFAULT false,
  thymum_velum DOUBLE PRECISION DEFAULT 0.0 UNIQUE,
  desino_adimpleo TIMESTAMP,
  cursus_viscus SMALLINT,
  crapula_delectus_alienus NUMERIC(10,2) DEFAULT 0.00,
  aestivus_sublime DOUBLE PRECISION,
  crustulum_commodi NUMERIC(10,2) NOT NULL UNIQUE,
  validus_alius TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  tutamen_cura UUID NOT NULL UNIQUE,
  audentia_coniuratio TIMESTAMP,
  ademptio UUID NOT NULL DEFAULT gen_random_uuid(),
  repellendus_similique_trepide INTEGER,
  aequus_studio_explicabo TIMESTAMP,
  tredecim_cuius INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  utroque_vociferor_342_id INTEGER REFERENCES utroque_vociferor_342(id)
);
