-- Migration: rls_policy_admoveo_tero_praesentium
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE adaugeo_causa_463 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_adaugeo_causa_463_502" ON adaugeo_causa_463 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_adaugeo_causa_463_781" ON adaugeo_causa_463 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_adaugeo_causa_463_219" ON adaugeo_causa_463 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_adaugeo_causa_463_871" ON adaugeo_causa_463 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
