-- Migration: create_view_decerno_crudelis_maiores
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_aureus_cena_384 AS
SELECT a.id, a.vulgus_amplus_sursum, a.aut_arx_caput, b.id, b.vociferor_damnatio, b.bibo_quaerat
FROM crur_atqui_364 a
CROSS JOIN aegrotatio_acies_136 b
LIMIT 1000;
