-- Migration: create_table_velit_clarus_hic
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE ipsum_nesciunt_427 (
  id SERIAL PRIMARY KEY,
  perferendis_ancilla_dolorem JSONB,
  balbus_unus_conicio INT[],
  tepidus DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  desolo_defleo_410_id INTEGER REFERENCES desolo_defleo_410(id)
);
