-- Migration: create_index_stabilis_statim_tutis
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_utroque_vociferor_342_adinventitias_quasi_sponte ON utroque_vociferor_342 (adinventitias_quasi, sponte);
