-- Migration: create_table_socius_adamo_quae
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE thema_suppellex_87 (
  id SERIAL PRIMARY KEY,
  confero TEXT,
  tubineus_bibo INTEGER NOT NULL DEFAULT 0,
  desino_vomica_alter TIMESTAMPTZ NOT NULL,
  inflammatio NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  autem_tres_magnam INET NOT NULL DEFAULT '0.0.0.0'::inet,
  custodia_voco_defero INTEGER,
  uxor_consectetur_agnosco BYTEA,
  tergo_creber UUID,
  conturbo_error_speciosus BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
