-- Migration: create_table_asporto_volo_defessus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE sollers_adflicto_598 (
  id SERIAL PRIMARY KEY,
  deduco_degenero_aestus REAL NOT NULL DEFAULT 0.0,
  utpote_carcer_ipsa SMALLINT,
  administratio_turpis_debitis TIMESTAMP DEFAULT NOW(),
  audentia_audio BIGINT,
  administratio NUMERIC(10,2) NOT NULL,
  certus_acquiro BYTEA NOT NULL,
  basium_conservo_antea INTEGER NOT NULL,
  auctus_amiculum CIDR,
  trucido_adstringo_tametsi CIDR,
  ademptio_nisi_aspernatur REAL DEFAULT 0.0,
  beneficium_arbor_tempore JSONB NOT NULL DEFAULT '{}'::jsonb,
  aro REAL,
  cultura_vorax TIMESTAMPTZ,
  veritas BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
