-- Migration: create_table_aperiam_currus_caritas
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vulnus_tantillus_645 (
  id SERIAL PRIMARY KEY,
  addo JSON NOT NULL,
  cornu SMALLINT DEFAULT 0,
  vesco DATE NOT NULL,
  tamisium MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  id_et_aqua TEXT NOT NULL DEFAULT 'default_text',
  bellicus_sono_aeternus NUMERIC(10,2),
  patruus_astrum BYTEA,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
