-- Migration: rls_policy_deleo_supra_deputo
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE labore_tendo_619 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_labore_tendo_619_366" ON labore_tendo_619 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_labore_tendo_619_182" ON labore_tendo_619 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_labore_tendo_619_686" ON labore_tendo_619 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_labore_tendo_619_994" ON labore_tendo_619 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
