-- Migration: rls_policy_desparatus_sui_carpo
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE patrocinor_usitas_946 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_patrocinor_usitas_946_283" ON patrocinor_usitas_946 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_patrocinor_usitas_946_378" ON patrocinor_usitas_946 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_patrocinor_usitas_946_103" ON patrocinor_usitas_946 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_patrocinor_usitas_946_719" ON patrocinor_usitas_946 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
