-- Migration: rls_policy_spiritus_delectatio_debitis
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE ambulo_aetas_593 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_ambulo_aetas_593_963" ON ambulo_aetas_593 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_ambulo_aetas_593_499" ON ambulo_aetas_593 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_ambulo_aetas_593_616" ON ambulo_aetas_593 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_ambulo_aetas_593_335" ON ambulo_aetas_593 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
