-- Migration: create_index_comburo_vilis_ulciscor
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_maiores_confido_323_conqueror_sulum_concedo_temeritas ON maiores_confido_323 (conqueror_sulum, concedo_temeritas);
