-- Migration: rls_policy_tendo_quia_tempus
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE strues_averto_536 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_strues_averto_536_313" ON strues_averto_536 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_strues_averto_536_654" ON strues_averto_536 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_strues_averto_536_232" ON strues_averto_536 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_strues_averto_536_15" ON strues_averto_536 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
