-- Migration: rls_policy_coerceo_architecto_calamitas
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE depopulo_ademptio_63 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_depopulo_ademptio_63_876" ON depopulo_ademptio_63 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_depopulo_ademptio_63_781" ON depopulo_ademptio_63 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_depopulo_ademptio_63_16" ON depopulo_ademptio_63 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_depopulo_ademptio_63_817" ON depopulo_ademptio_63 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
