-- Migration: create_table_utrum_templum_magnam
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE crur_atqui_364 (
  id SERIAL PRIMARY KEY,
  vulgus_amplus_sursum VARCHAR(255) DEFAULT 'default',
  aut_arx_caput JSONB DEFAULT '{}'::jsonb,
  vesco DOUBLE PRECISION,
  conforto INT[] DEFAULT ARRAY[]::INT[],
  tepidus_verto_expedita INTEGER UNIQUE,
  abundans NUMERIC(10,2) NOT NULL,
  venio CIDR,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
