-- Migration: rls_policy_natus_cena_sopor
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE sui_acer_419 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_sui_acer_419_538" ON sui_acer_419 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_sui_acer_419_60" ON sui_acer_419 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_sui_acer_419_555" ON sui_acer_419 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_sui_acer_419_791" ON sui_acer_419 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
