-- Migration: create_index_taceo_tenetur_ventosus
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_sint_voluptatem_847_calamitas_similique_175_id ON sint_voluptatem_847 (calamitas_similique_175_id) WHERE calamitas_similique_175_id IS NOT NULL;
