-- Migration: create_index_patior_sulum_absens
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_cervus_crur_422_suspendo_solio_conspergo ON cervus_crur_422 (suspendo_solio, conspergo) WHERE suspendo_solio IS NOT NULL;
