-- Migration: trigger_function_adsuesco_asporto_tego
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_copiose_defetiscor_711()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.id IS NULL THEN
    RAISE EXCEPTION 'id cannot be null on tabernus_fugiat_216';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_tabernus_fugiat_216_937
  BEFORE INSERT OR UPDATE ON tabernus_fugiat_216
  FOR EACH ROW EXECUTE FUNCTION fn_copiose_defetiscor_711();
