-- Migration: create_view_bene_tui_clam
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_defleo_conventus_629 AS
SELECT a.id, a.auxilium, a.voluptate, b.id, b.ambulo_calcar_abduco, b.tamquam_vigilo_adnuo
FROM derelinquo_curiositas_411 a
CROSS JOIN decretum_xiphias_835 b
LIMIT 1000;
