-- Migration: trigger_function_tum_conturbo_unde
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_autem_deporto_741()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_canis_adicio_18_493
  BEFORE UPDATE ON canis_adicio_18
  FOR EACH ROW EXECUTE FUNCTION fn_autem_deporto_741();
