-- Migration: rls_policy_ait_decor_ulciscor
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE constans_terreo_554 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_constans_terreo_554_310" ON constans_terreo_554 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_constans_terreo_554_528" ON constans_terreo_554 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_constans_terreo_554_216" ON constans_terreo_554 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_constans_terreo_554_884" ON constans_terreo_554 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
