-- Migration: rls_policy_inventore_animus_amplexus
-- Type: rls_policy
-- Generated by stress-generator

CREATE POLICY "policy_select_confugo_dolorem_615_328" ON confugo_dolorem_615 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_confugo_dolorem_615_159" ON confugo_dolorem_615 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_confugo_dolorem_615_168" ON confugo_dolorem_615 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_confugo_dolorem_615_662" ON confugo_dolorem_615 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
