-- Migration: create_table_officiis_spiculum_acceptus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE derideo_coerceo_285 (
  id SERIAL PRIMARY KEY,
  desolo_admoneo BOOLEAN NOT NULL DEFAULT false,
  voro_carbo REAL NOT NULL DEFAULT 0.0,
  ratione_recusandae JSON,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  projects_id INTEGER REFERENCES projects(id)
);
