-- Migration: rls_policy_caritas_voluptatum_theca
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE infit_arbor_134 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_infit_arbor_134_499" ON infit_arbor_134 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_infit_arbor_134_475" ON infit_arbor_134 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_infit_arbor_134_110" ON infit_arbor_134 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_infit_arbor_134_560" ON infit_arbor_134 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
