-- Migration: rls_policy_assumenda_creo_conor
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE confero_vestrum_225 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_confero_vestrum_225_990" ON confero_vestrum_225 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_confero_vestrum_225_611" ON confero_vestrum_225 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_confero_vestrum_225_371" ON confero_vestrum_225 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_confero_vestrum_225_772" ON confero_vestrum_225 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
