-- Migration: create_table_aliquam_quas_cetera
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE desolo_defleo_410 (
  id SERIAL PRIMARY KEY,
  adversus_aedificium TEXT,
  stips_caterva NUMERIC(10,2) NOT NULL,
  voluptatum_curso DATE DEFAULT CURRENT_DATE,
  animus UUID,
  tredecim INT[],
  debilito_censura REAL DEFAULT 0.0,
  deserunt_delibero JSONB,
  stultus_sum TIMESTAMP,
  valetudo_subito MACADDR NOT NULL,
  articulus_admoveo_nihil TEXT[] DEFAULT ARRAY[]::TEXT[],
  comburo_sumo TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  crur_amaritudo INET,
  voveo REAL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  utique_tener_362_id INTEGER REFERENCES utique_tener_362(id)
);
