-- Migration: rls_policy_trepide_suus_vox
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE derideo_coerceo_285 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_derideo_coerceo_285_332" ON derideo_coerceo_285 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_derideo_coerceo_285_471" ON derideo_coerceo_285 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_derideo_coerceo_285_315" ON derideo_coerceo_285 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_derideo_coerceo_285_700" ON derideo_coerceo_285 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
