-- Migration: create_table_agnitio_arma_decerno
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE adflicto_acer_774 (
  id SERIAL PRIMARY KEY,
  pecto_cursus TEXT NOT NULL DEFAULT 'default_text',
  damnatio_facilis_demoror DATE NOT NULL,
  vester_vivo JSONB DEFAULT '{}'::jsonb,
  nisi BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  depopulo_ademptio_63_id INTEGER REFERENCES depopulo_ademptio_63(id)
);
