-- Migration: create_table_tripudio_animadverto_tabesco
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE confugo_dolorem_615 (
  id SERIAL PRIMARY KEY,
  desino_admitto TEXT,
  acidus UUID DEFAULT gen_random_uuid(),
  pecus BOOLEAN,
  tantillus_antea INET,
  crepusculum_aeger_accusantium CIDR,
  adaugeo_vito REAL NOT NULL DEFAULT 0.0,
  cometes_ubi_vinitor MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  abstergo_sumptus_suffoco DOUBLE PRECISION NOT NULL,
  decipio BOOLEAN,
  corroboro INT[] DEFAULT ARRAY[]::INT[],
  arcus_volo UUID DEFAULT gen_random_uuid(),
  tantillus_tego NUMERIC(10,2) NOT NULL,
  absconditus SMALLINT NOT NULL,
  vehemens_verbera_combibo REAL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  adaugeo_causa_463_id INTEGER REFERENCES adaugeo_causa_463(id)
);
