-- Migration: trigger_function_similique_iusto_sequi
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_defaeco_placeat_688()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_audax_antea_139_513
  BEFORE UPDATE ON audax_antea_139
  FOR EACH ROW EXECUTE FUNCTION fn_defaeco_placeat_688();
