-- Migration: create_index_averto_bene_sto
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_vigor_quisquam_335_quam_expedita_varietas_antiquus_crux_the ON vigor_quisquam_335 (quam_expedita_varietas, antiquus_crux_thema, ademptio_molestiae_tempus) WHERE quam_expedita_varietas IS NOT NULL;
