-- Migration: create_table_astrum_cibo_articulus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vulpes_caute_724 (
  id SERIAL PRIMARY KEY,
  ver TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sui JSON DEFAULT '{}'::json,
  ipsum BOOLEAN NOT NULL DEFAULT false,
  cupio SMALLINT,
  alienus_suasoria BIGINT NOT NULL DEFAULT 0,
  una_antepono JSON,
  depopulo_vestigium JSONB,
  trado UUID,
  reiciendis MACADDR NOT NULL,
  crastinus CIDR,
  ventito_desolo UUID NOT NULL,
  torrens_tergiversatio INET NOT NULL DEFAULT '0.0.0.0'::inet,
  aut_aperte_voluptates MACADDR NOT NULL,
  impedit_admoneo BYTEA,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
