-- Migration: create_table_unde_amo_vinitor
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE carbo_denuncio_886 (
  id SERIAL PRIMARY KEY,
  alo_demonstro_vulgaris INET,
  termes_tepidus SMALLINT NOT NULL,
  pecco_laborum JSONB DEFAULT '{}'::jsonb,
  aperte_tener INT[] NOT NULL,
  amplexus_victus BIGINT,
  defleo_assumenda_cenaculum JSONB,
  viduo_verecundia_vindico BOOLEAN,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
