-- Migration: create_table_theologus_debeo_toties
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE quae_ustulo_571 (
  id SERIAL PRIMARY KEY,
  strenuus_spes_bibo DOUBLE PRECISION,
  xiphias_administratio TEXT[],
  taceo_utrimque DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
