-- Migration: create_table_pecus_arguo_beatae
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE utique_tener_362 (
  id SERIAL PRIMARY KEY,
  testimonium JSON,
  adaugeo UUID,
  tego_decens BYTEA,
  suppono CIDR,
  civis_commodo_spoliatio JSON,
  voro_tenetur_vilitas SMALLINT NOT NULL DEFAULT 0,
  conor_unus CIDR,
  tristis_collum INT[],
  communis CIDR NOT NULL,
  bellicus JSONB,
  suadeo_vilicus_iste NUMERIC(10,2) NOT NULL UNIQUE,
  ventosus_theatrum_nulla REAL NOT NULL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  sui_acer_419_id INTEGER REFERENCES sui_acer_419(id)
);
