-- Migration: trigger_function_asporto_adnuo_sunt
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_sufficio_talis_678()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.ventosus IS NULL THEN
    RAISE EXCEPTION 'ventosus cannot be null on occaecati_vilicus_575';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_occaecati_vilicus_575_253
  BEFORE INSERT OR UPDATE ON occaecati_vilicus_575
  FOR EACH ROW EXECUTE FUNCTION fn_sufficio_talis_678();
