-- Migration: create_table_cauda_vallum_deprecator
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE clarus_spoliatio_316 (
  id SERIAL PRIMARY KEY,
  tempus VARCHAR(255),
  candidus_provident JSONB NOT NULL,
  deprecator_statim INTEGER DEFAULT 0 UNIQUE,
  deorsum INET UNIQUE,
  cerno_possimus TEXT[] DEFAULT ARRAY[]::TEXT[],
  ter_velociter_concido TEXT[] DEFAULT ARRAY[]::TEXT[],
  alioqui_amplitudo_ademptio INTEGER,
  tergeo_facere_thema NUMERIC(10,2),
  vomica_cunctatio_tenax INTEGER NOT NULL UNIQUE,
  perferendis_animadverto INT[],
  crinis BYTEA NOT NULL,
  vox_benigne DATE,
  aggredior TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
