-- Migration: create_table_colo_defaeco_tibi
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE curso_audax_111 (
  id SERIAL PRIMARY KEY,
  tracto TEXT[],
  temporibus_conscendo_defetiscor NUMERIC(10,2) NOT NULL,
  vox REAL,
  amplitudo INTEGER,
  ulterius NUMERIC(10,2) NOT NULL,
  socius_ad TEXT DEFAULT 'default_text',
  apto_speculum NUMERIC(10,2) DEFAULT 0.00 UNIQUE,
  arguo_cotidie DOUBLE PRECISION DEFAULT 0.0,
  undique_tardus JSON,
  votum DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  amiculum_chirographum MACADDR UNIQUE,
  succedo_porro_dolore UUID DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
