-- Migration: create_view_consequatur_usque_aliquid
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_pauci_appono_391 AS
SELECT a.id, a.credo_spoliatio, a.utroque_vinco, b.id, b.demo_vesco, b.caput_utilis_triduana
FROM canis_adicio_18 a
CROSS JOIN alo_atrox_797 b
LIMIT 1000;
