-- Migration: trigger_function_alveus_vesco_aqua
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_soluta_conitor_893()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on adhaero_averto_179 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_adhaero_averto_179_292
  AFTER INSERT OR UPDATE OR DELETE ON adhaero_averto_179
  FOR EACH ROW EXECUTE FUNCTION fn_soluta_conitor_893();
