-- Migration: create_table_cognatus_sublime_texo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE adfero_annus_986 (
  id SERIAL PRIMARY KEY,
  amissio BYTEA NOT NULL DEFAULT '\x00'::bytea UNIQUE,
  adstringo INTEGER DEFAULT 0,
  vilicus INT[],
  suscipio_defero CIDR NOT NULL,
  averto DATE,
  pecto_stultus DATE NOT NULL,
  delego CIDR NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  projects_id INTEGER REFERENCES projects(id)
);
