-- Migration: create_table_certe_cupio_animus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE illum_abscido_325 (
  id SERIAL PRIMARY KEY,
  sub_creta UUID,
  pax REAL NOT NULL,
  earum_demum_acies TIMESTAMP,
  pecus_teneo CIDR NOT NULL UNIQUE,
  absens DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  victus TIMESTAMP,
  cohibeo INET,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
