-- Migration: create_view_cruentus_calcar_astrum
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_paens_asper_124 AS
SELECT a.id, a.tutis_theca, a.carus_celebrer_a, b.id, b.name, b.description
FROM corrupti_thema_368 a
CROSS JOIN projects b
LIMIT 1000;
