-- Migration: create_index_fugiat_censura_corporis
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_bellum_correptius_485_pecto_capillus_ambitus_custodia_antiq ON bellum_correptius_485 (pecto_capillus_ambitus, custodia_antiquus_ciminatio, accusator_comminor);
