-- Migration: rls_policy_teneo_vetus_bardus
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE absum_aequus_393 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_absum_aequus_393_938" ON absum_aequus_393 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_absum_aequus_393_276" ON absum_aequus_393 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_absum_aequus_393_332" ON absum_aequus_393 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_absum_aequus_393_701" ON absum_aequus_393 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
