-- Migration: create_index_undique_demitto_thermae
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_confero_vestrum_225_sint_circumvenio_totam_caritas ON confero_vestrum_225 (sint_circumvenio_totam, caritas);
