-- Migration: create_index_quas_tergo_desidero
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_tener_nulla_782_tot_tergo_vulnus_tremo_tutis_tandem_ver_tem ON tener_nulla_782 (tot_tergo, vulnus_tremo_tutis, tandem_ver_tempora);
