-- Migration: trigger_function_tabgo_admoneo_admiratio
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_decipio_commemoro_526()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_coepi_demitto_168_688
  BEFORE UPDATE ON coepi_demitto_168
  FOR EACH ROW EXECUTE FUNCTION fn_decipio_commemoro_526();
