-- Migration: create_table_vitiosus_synagoga_amor
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE super_sordeo_748 (
  id SERIAL PRIMARY KEY,
  capillus TIMESTAMP NOT NULL,
  absum REAL,
  sed TIMESTAMPTZ NOT NULL,
  excepturi_vesica_beatus NUMERIC(10,2),
  vereor_cotidie SMALLINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
