-- Migration: trigger_function_neque_cervus_tredecim
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_cognomen_urbs_781()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_atque_vitium_693_930
  BEFORE UPDATE ON atque_vitium_693
  FOR EACH ROW EXECUTE FUNCTION fn_cognomen_urbs_781();
