-- Migration: create_table_stipes_stabilis_ipsum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE canis_dolorum_322 (
  id SERIAL PRIMARY KEY,
  utilis_molestiae MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  solutio_thalassinus BYTEA NOT NULL,
  amor_civitas SMALLINT DEFAULT 0 UNIQUE,
  pel_suggero DOUBLE PRECISION DEFAULT 0.0,
  tametsi_baiulus_confugo TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  vinum_saepe_877_id INTEGER REFERENCES vinum_saepe_877(id)
);
