-- Migration: rls_policy_sustineo_benevolentia_aeternus
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE atque_vitium_693 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_atque_vitium_693_95" ON atque_vitium_693 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_atque_vitium_693_319" ON atque_vitium_693 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_atque_vitium_693_992" ON atque_vitium_693 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_atque_vitium_693_678" ON atque_vitium_693 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
