-- Migration: trigger_function_cubicularis_doloribus_thymbra
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_utrimque_occaecati_674()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on conicio_centum_966 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_conicio_centum_966_804
  AFTER INSERT OR UPDATE OR DELETE ON conicio_centum_966
  FOR EACH ROW EXECUTE FUNCTION fn_utrimque_occaecati_674();
