-- Migration: create_table_quisquam_animus_voro
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE careo_turbo_210 (
  id SERIAL PRIMARY KEY,
  culpa_verumtamen_sol VARCHAR(255) NOT NULL DEFAULT 'default',
  admoneo_derideo INTEGER,
  arguo_cornu_corroboro BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  eaque_utpote_741_id INTEGER REFERENCES eaque_utpote_741(id)
);
