-- Migration: create_table_earum_cariosus_contabesco
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE utique_voluntarius_177 (
  id SERIAL PRIMARY KEY,
  cultura JSONB,
  tolero_virga TEXT NOT NULL DEFAULT 'default_text',
  apparatus UUID NOT NULL UNIQUE,
  veniam_crebro SMALLINT DEFAULT 0,
  odio_conservo_thermae JSON NOT NULL,
  cupio_vita JSON NOT NULL DEFAULT '{}'::json,
  audacia_adulatio NUMERIC(10,2) NOT NULL,
  aggero_decimus BIGINT DEFAULT 0,
  cubicularis JSONB,
  dicta VARCHAR(255),
  labore_vitiosus_administratio INTEGER DEFAULT 0,
  adipisci_vindico CIDR DEFAULT '0.0.0.0/0'::cidr,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  eaque_utpote_741_id INTEGER REFERENCES eaque_utpote_741(id)
);
