-- Migration: create_index_fugiat_accedo_causa
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_fuga_verto_346_conventus_nobis_ratione ON fuga_verto_346 (conventus_nobis_ratione) WHERE conventus_nobis_ratione IS NOT NULL;
