-- Migration: rls_policy_taedium_templum_pectus
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE coepi_demitto_168 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_coepi_demitto_168_894" ON coepi_demitto_168 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_coepi_demitto_168_919" ON coepi_demitto_168 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_coepi_demitto_168_95" ON coepi_demitto_168 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_coepi_demitto_168_544" ON coepi_demitto_168 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
