-- Migration: create_table_succedo_convoco_volup
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE animus_deputo_35 (
  id SERIAL PRIMARY KEY,
  somniculosus TIMESTAMPTZ,
  terga_vigor_varius NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  comparo DATE,
  illo INTEGER NOT NULL DEFAULT 0,
  avarus_abscido_tot REAL NOT NULL UNIQUE,
  ancilla_urbanus DOUBLE PRECISION DEFAULT 0.0,
  suspendo DOUBLE PRECISION NOT NULL,
  temptatio_laudantium_tepidus JSONB UNIQUE,
  addo DOUBLE PRECISION,
  cunae BYTEA DEFAULT '\x00'::bytea,
  vetus INET NOT NULL,
  vapulus JSON NOT NULL,
  calcar DATE NOT NULL UNIQUE,
  cur_brevis INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
