-- Migration: create_table_blanditiis_asper_capillus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE aequitas_temporibus_486 (
  id SERIAL PRIMARY KEY,
  vetus_verbum BYTEA NOT NULL,
  quia_dens DATE NOT NULL,
  centum_amaritudo_conservo DATE,
  aer_ater MACADDR NOT NULL,
  coaegresco_una TEXT[] NOT NULL,
  natus_triumphus REAL,
  ventosus TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
