-- Migration: trigger_function_dedico_cervus_crudelis
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_uxor_deorsum_542()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.possimus_aggredior IS NULL THEN
    RAISE EXCEPTION 'possimus_aggredior cannot be null on demens_aliqua_626';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_demens_aliqua_626_919
  BEFORE INSERT OR UPDATE ON demens_aliqua_626
  FOR EACH ROW EXECUTE FUNCTION fn_uxor_deorsum_542();
