-- Migration: create_index_adimpleo_voluptatem_accommodo
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_vaco_thymbra_505_volva_reiciendis_vorax_sordeo ON vaco_thymbra_505 (volva_reiciendis, vorax_sordeo);
