-- Migration: create_index_cimentarius_speculum_accusamus
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_derelinquo_curiositas_411_voluptate_auxilium_adinventitias_ ON derelinquo_curiositas_411 (voluptate, auxilium, adinventitias_adnuo);
