-- Migration: create_table_terminatio_cornu_voluptatum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE desidero_textus_151 (
  id SERIAL PRIMARY KEY,
  confugo DOUBLE PRECISION,
  advoco_aut_sollicito CIDR,
  tondeo INET,
  recusandae_admitto NUMERIC(10,2),
  turba VARCHAR(255),
  tantillus_adversus_summopere JSON NOT NULL,
  depraedor_defleo SMALLINT NOT NULL,
  statua INT[] NOT NULL,
  pauci_aro JSON,
  censura_vulticulus VARCHAR(255) DEFAULT 'default',
  sollers_utrum_benigne TEXT[] DEFAULT ARRAY[]::TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
