-- Migration: create_table_volup_villa_cena
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE utrum_amaritudo_141 (
  id SERIAL PRIMARY KEY,
  facilis_civitas_consequatur TIMESTAMP DEFAULT NOW(),
  cohibeo_audentia_tum BYTEA NOT NULL DEFAULT '\x00'::bytea,
  porro_denego NUMERIC(10,2),
  spoliatio_defendo TIMESTAMP UNIQUE,
  tutis_conspergo_adipisci TEXT[] DEFAULT ARRAY[]::TEXT[],
  claudeo_necessitatibus_cupressus INTEGER,
  ascit DOUBLE PRECISION NOT NULL,
  color TEXT NOT NULL,
  tribuo_circumvenio_audacia TEXT[] NOT NULL UNIQUE,
  talus_aetas JSON DEFAULT '{}'::json,
  amoveo DOUBLE PRECISION DEFAULT 0.0,
  cruciamentum_surculus INT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  celer_bellicus_765_id INTEGER REFERENCES celer_bellicus_765(id)
);
