-- Migration: trigger_function_aequus_avarus_conqueror
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_turpis_degero_218()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.name IS NULL THEN
    RAISE EXCEPTION 'name cannot be null on organisations';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_organisations_134
  BEFORE INSERT OR UPDATE ON organisations
  FOR EACH ROW EXECUTE FUNCTION fn_turpis_degero_218();
