-- Migration: create_table_stella_theologus_atqui
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE voluptates_sursum_915 (
  id SERIAL PRIMARY KEY,
  summopere_claustrum_ipsa DOUBLE PRECISION,
  thymbra_depopulo_creber CIDR DEFAULT '0.0.0.0/0'::cidr,
  studio TIMESTAMP,
  quia_tumultus_tempore NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  eum_annus JSON NOT NULL,
  conscendo_vulgaris_defleo CIDR,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
