-- Migration: create_table_constans_super_clibanus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE amicitia_thesaurus_179 (
  id SERIAL PRIMARY KEY,
  alveus BOOLEAN NOT NULL,
  sordeo_bardus TIMESTAMPTZ NOT NULL DEFAULT NOW() UNIQUE,
  acquiro BIGINT,
  congregatio_caveo_crastinus NUMERIC(10,2),
  debeo_claustrum INT[] NOT NULL DEFAULT ARRAY[]::INT[],
  varius_thesaurus DATE DEFAULT CURRENT_DATE,
  causa_apud CIDR NOT NULL,
  accusamus INT[],
  soleo_tricesimus SMALLINT DEFAULT 0,
  patria_pauci_sono BIGINT NOT NULL,
  adipiscor_aspernatur BYTEA,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  derideo_coerceo_285_id INTEGER REFERENCES derideo_coerceo_285(id)
);
