-- Migration: create_table_commodi_illum_ipsam
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE socius_at_872 (
  id SERIAL PRIMARY KEY,
  vivo JSONB,
  toties_volutabrum_desipio UUID NOT NULL DEFAULT gen_random_uuid(),
  alii_cura CIDR NOT NULL DEFAULT '0.0.0.0/0'::cidr UNIQUE,
  utilis INTEGER NOT NULL DEFAULT 0,
  testimonium_canis DOUBLE PRECISION,
  usitas NUMERIC(10,2),
  tempore_amiculum_dicta CIDR NOT NULL,
  cruentus_ubi JSONB,
  culpo_concedo_deprimo NUMERIC(10,2),
  amissio_capitulus INT[] DEFAULT ARRAY[]::INT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  organisations_id INTEGER REFERENCES organisations(id)
);
