-- Migration: create_view_cilicium_cunctatio_canonicus
-- Type: create_view
-- Generated by stress-generator

CREATE MATERIALIZED VIEW vw_synagoga_stillicidium_212 AS
SELECT a.id, a.defungo_in, a.comis, b.id, b.desolo_admoneo, b.voro_carbo
FROM occaecati_vilicus_575 a
CROSS JOIN derideo_coerceo_285 b
LIMIT 1000;
