-- Migration: rls_policy_alias_cruciamentum_summisse
-- Type: rls_policy
-- Generated by stress-generator

CREATE POLICY "policy_select_coerceo_suggero_68_881" ON coerceo_suggero_68 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_coerceo_suggero_68_891" ON coerceo_suggero_68 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_coerceo_suggero_68_197" ON coerceo_suggero_68 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_coerceo_suggero_68_614" ON coerceo_suggero_68 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
