-- Migration: trigger_function_admoveo_totidem_tremo
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_sperno_dapifer_559()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on alo_atrox_797 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_alo_atrox_797_58
  AFTER INSERT OR UPDATE OR DELETE ON alo_atrox_797
  FOR EACH ROW EXECUTE FUNCTION fn_sperno_dapifer_559();
