-- Migration: create_table_amor_volup_natus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tolero_trans_708 (
  id SERIAL PRIMARY KEY,
  valetudo_cursim_cupio UUID,
  numquam_tantillus_balbus REAL NOT NULL,
  ustilo_ustilo_adversus CIDR NOT NULL UNIQUE,
  complectus_delibero_statim INT[] NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  demens_aliqua_626_id INTEGER REFERENCES demens_aliqua_626(id)
);
