-- Migration: create_table_aedificium_voluptas_contigo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE decumbo_suscipio_693 (
  id SERIAL PRIMARY KEY,
  somniculosus NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  cervus_demitto TIMESTAMP,
  earum_admoneo SMALLINT,
  commodi_causa UUID,
  amissio_tergeo_titulus INET,
  sint_defungo JSON UNIQUE,
  clarus_impedit INTEGER NOT NULL,
  arbustum MACADDR,
  ustilo_tribuo DOUBLE PRECISION DEFAULT 0.0 UNIQUE,
  appositus BOOLEAN,
  sulum_amplexus_tabgo BOOLEAN NOT NULL,
  cibo INT[],
  voluptatem_voluptates_aedificium CIDR NOT NULL,
  vomito_vere UUID,
  degenero_adsidue_curso UUID NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
