-- Migration: rls_policy_calamitas_aperio_vindico
-- Type: rls_policy
-- Generated by stress-generator

CREATE POLICY "policy_select_absum_aequus_393_631" ON absum_aequus_393 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_absum_aequus_393_86" ON absum_aequus_393 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_absum_aequus_393_946" ON absum_aequus_393 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_absum_aequus_393_292" ON absum_aequus_393 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
