-- Migration: create_table_quasi_terminatio_nesciunt
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE sint_voluptatem_847 (
  id SERIAL PRIMARY KEY,
  terra_termes_defungo DATE DEFAULT CURRENT_DATE,
  denuo BYTEA DEFAULT '\x00'::bytea,
  territo_vulgaris_illum TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  calamitas_similique_175_id INTEGER REFERENCES calamitas_similique_175(id)
);
