-- Migration: create_table_acervus_numquam_vilis
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE alo_atrox_797 (
  id SERIAL PRIMARY KEY,
  demo_vesco VARCHAR(255),
  caput_utilis_triduana SMALLINT,
  thermae TIMESTAMP NOT NULL,
  thymum_usitas_adulatio REAL,
  eius_vulnus INTEGER NOT NULL,
  vir MACADDR NOT NULL,
  sortitus_denuo DATE,
  demens JSON DEFAULT '{}'::json,
  conspergo INET DEFAULT '0.0.0.0'::inet,
  theca_tabesco NUMERIC(10,2) DEFAULT 0.00,
  patruus_doloribus TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
