-- Migration: trigger_function_vulgus_amoveo_officia
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_vaco_ulterius_506()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_occaecati_vilicus_575_490
  BEFORE UPDATE ON occaecati_vilicus_575
  FOR EACH ROW EXECUTE FUNCTION fn_vaco_ulterius_506();
