-- Migration: create_table_vetus_absens_verus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE delego_peior_422 (
  id SERIAL PRIMARY KEY,
  cornu_tergo_comparo UUID UNIQUE,
  valetudo_strues BIGINT,
  usque TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
