-- Migration: create_table_apparatus_canis_defessus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE adhaero_averto_179 (
  id SERIAL PRIMARY KEY,
  dolor_demoror BOOLEAN,
  usque BYTEA NOT NULL,
  basium_decet_advoco CIDR,
  tam_quaerat INET,
  depereo_delectatio_territo CIDR DEFAULT '0.0.0.0/0'::cidr,
  tardus_tondeo_adduco UUID NOT NULL UNIQUE,
  infit_avaritia_comes BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
