-- Migration: create_table_tempore_defaeco_tergeo
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE nisi_laudantium_561 (
  id SERIAL PRIMARY KEY,
  tibi_centum_tremo JSONB DEFAULT '{}'::jsonb,
  suffragium_tertius_ea UUID,
  bos NUMERIC(10,2) NOT NULL,
  curiositas_repellat INET,
  mollitia_odio BIGINT UNIQUE,
  tripudio BOOLEAN DEFAULT false,
  curtus MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  denuncio_appello VARCHAR(255) NOT NULL,
  teneo_articulus_pel INTEGER NOT NULL,
  adstringo BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  spectaculum_tantum_791_id INTEGER REFERENCES spectaculum_tantum_791(id)
);
