-- Migration: trigger_function_utroque_surgo_amplexus
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_amiculum_tumultus_671()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_accedo_taceo_834_697
  BEFORE UPDATE ON accedo_taceo_834
  FOR EACH ROW EXECUTE FUNCTION fn_amiculum_tumultus_671();
