-- Migration: create_table_argentum_decerno_possimus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE depopulo_ademptio_63 (
  id SERIAL PRIMARY KEY,
  exercitationem DATE UNIQUE,
  vix_laborum INT[],
  vomica_cauda_solium SMALLINT,
  consectetur_amplitudo BIGINT DEFAULT 0,
  eos_amplus MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  aggredior_defungo JSONB,
  deinde_cupiditas_soleo JSON,
  admoneo_terror SMALLINT DEFAULT 0,
  earum_bardus_utpote MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  ter_acsi_aedificium UUID NOT NULL,
  solum CIDR,
  eos TIMESTAMPTZ NOT NULL,
  crustulum_veritas_expedita BIGINT NOT NULL,
  ventus_charisma_vorago INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
