-- Migration: create_table_acsi_brevis_callide
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE fuga_verto_346 (
  id SERIAL PRIMARY KEY,
  defero_caelestis_defero INTEGER,
  conventus_nobis_ratione TEXT NOT NULL DEFAULT 'default_text',
  cuppedia VARCHAR(255) NOT NULL,
  tandem SMALLINT NOT NULL DEFAULT 0,
  demens JSON,
  decet_cui JSON DEFAULT '{}'::json,
  corroboro_cerno_sequi DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
