-- Migration: create_table_utor_et_concido
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE commodo_denique_597 (
  id SERIAL PRIMARY KEY,
  coadunatio_adsidue TEXT,
  dolores_arca JSON,
  tendo TEXT DEFAULT 'default_text',
  corroboro DATE,
  aurum_cerno CIDR,
  cibo_villa MACADDR,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
