-- Migration: create_table_qui_voluptate_delego
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tui_quaerat_563 (
  id SERIAL PRIMARY KEY,
  ocer_nobis_vulariter BYTEA,
  patria INT[] NOT NULL,
  vulnero TEXT[] NOT NULL,
  adnuo_deficio REAL NOT NULL,
  desidero REAL NOT NULL,
  repellat NUMERIC(10,2),
  tui_assentator_accusantium INET NOT NULL,
  vitium_facilis_deporto DATE,
  nostrum_optio_conspergo VARCHAR(255) UNIQUE,
  uxor_vacuus DOUBLE PRECISION,
  tabula TIMESTAMPTZ NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
