-- Migration: create_table_magni_culpa_volaticus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE repellendus_tamen_927 (
  id SERIAL PRIMARY KEY,
  conitor_consectetur_illo DATE,
  conitor_enim_contigo TEXT DEFAULT 'default_text' UNIQUE,
  absque_vitiosus_dolorum TEXT[],
  contra_cavus_umquam TIMESTAMP,
  custodia VARCHAR(255),
  alienus_baiulus BIGINT,
  pauci JSON,
  spectaculum TIMESTAMP DEFAULT NOW(),
  at_cupiditate JSONB UNIQUE,
  non_theatrum_curtus UUID NOT NULL,
  derelinquo MACADDR,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
