-- Migration: rls_policy_creta_tantillus_crepusculum
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE animus_deputo_35 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_animus_deputo_35_969" ON animus_deputo_35 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_animus_deputo_35_810" ON animus_deputo_35 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_animus_deputo_35_751" ON animus_deputo_35 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_animus_deputo_35_760" ON animus_deputo_35 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
