-- Migration: create_index_ipsa_contigo_antea
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_patrocinor_usitas_946_sponte_cumque_accendo ON patrocinor_usitas_946 (sponte_cumque_accendo);
