-- Migration: trigger_function_aqua_utpote_attollo
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_approbo_depopulo_259()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on exercitationem_consuasor_792 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_exercitationem_consuasor_792_754
  AFTER INSERT OR UPDATE OR DELETE ON exercitationem_consuasor_792
  FOR EACH ROW EXECUTE FUNCTION fn_approbo_depopulo_259();
