-- Migration: create_table_tum_vinco_statua
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE adaugeo_causa_463 (
  id SERIAL PRIMARY KEY,
  talis_cursim_coniuratio TIMESTAMP NOT NULL DEFAULT NOW(),
  decens_surgo JSONB NOT NULL,
  omnis INT[],
  apostolus_sumptus_verbera BIGINT,
  deprimo_caritas_usus UUID,
  crinis TEXT[],
  aperte_volubilis_defetiscor SMALLINT DEFAULT 0,
  tricesimus_curvo BOOLEAN NOT NULL,
  adfectus BYTEA NOT NULL,
  numquam_ustilo_basium INTEGER DEFAULT 0,
  adflicto_animus_defero INT[] UNIQUE,
  vos TEXT[],
  deficio_ducimus_deporto REAL DEFAULT 0.0,
  baiulus_speculum_volubilis VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  fuga_verto_346_id INTEGER REFERENCES fuga_verto_346(id)
);
