-- Migration: create_table_curo_apto_arto
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE cultura_sustineo_965 (
  id SERIAL PRIMARY KEY,
  aqua_aequitas_labore TIMESTAMPTZ NOT NULL,
  depereo JSONB,
  conventus_acceptus JSONB DEFAULT '{}'::jsonb,
  cruentus INTEGER,
  defero_earum_tollo DATE NOT NULL,
  ater_confido_caecus TIMESTAMP,
  copia_voveo_paens DATE NOT NULL,
  delibero MACADDR,
  cinis_necessitatibus_anser REAL NOT NULL DEFAULT 0.0,
  anser_curia SMALLINT,
  pectus_acerbitas_vicinus REAL,
  deleo_curia MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  stella_delibero_aliquam INET DEFAULT '0.0.0.0'::inet,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  projects_id INTEGER REFERENCES projects(id)
);
