-- Migration: create_view_thymum_terebro_infit
-- Type: create_view
-- Generated by stress-generator

CREATE MATERIALIZED VIEW vw_blandior_somniculosus_484 AS
SELECT a.id, a.ars_collum_clam, a.mollitia_tristis, b.id, b.quam_expedita_varietas, b.ademptio_molestiae_tempus
FROM thesaurus_ipsum_397 a
CROSS JOIN vigor_quisquam_335 b
LIMIT 1000;
