-- Migration: create_table_comprehendo_vivo_venia
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE abduco_carbo_510 (
  id SERIAL PRIMARY KEY,
  vomer_consectetur UUID DEFAULT gen_random_uuid(),
  temporibus_architecto NUMERIC(10,2) DEFAULT 0.00 UNIQUE,
  colligo INTEGER NOT NULL,
  odio VARCHAR(255) NOT NULL,
  acerbitas_saepe DATE DEFAULT CURRENT_DATE,
  attero_strenuus JSON NOT NULL DEFAULT '{}'::json,
  amplus_sub_decimus INT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
