-- Migration: create_table_testimonium_decumbo_theologus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE cervus_crur_422 (
  id SERIAL PRIMARY KEY,
  summopere_pecus_collum CIDR NOT NULL UNIQUE,
  admoneo_causa VARCHAR(255) NOT NULL,
  defleo_corporis INTEGER UNIQUE,
  conspergo INT[] NOT NULL,
  abstergo_repellat INT[] NOT NULL,
  veniam VARCHAR(255) DEFAULT 'default' UNIQUE,
  claustrum_depereo NUMERIC(10,2) DEFAULT 0.00,
  suspendo_solio CIDR NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  bellum_correptius_485_id INTEGER REFERENCES bellum_correptius_485(id)
);
