-- Migration: create_table_tum_tergeo_compello
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE degenero_tersus_28 (
  id SERIAL PRIMARY KEY,
  suus JSONB DEFAULT '{}'::jsonb,
  cena DOUBLE PRECISION,
  theatrum SMALLINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  demonstro_sonitus_936_id INTEGER REFERENCES demonstro_sonitus_936(id)
);
