-- Migration: create_table_aptus_adaugeo_victus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE saepe_advoco_734 (
  id SERIAL PRIMARY KEY,
  fugit BIGINT,
  surculus BIGINT NOT NULL,
  suggero_adduco_clementia MACADDR,
  temporibus_surgo REAL NOT NULL,
  sunt_utor BOOLEAN,
  sonitus TEXT[] NOT NULL,
  est_valetudo_comprehendo VARCHAR(255) DEFAULT 'default',
  studio_valens_defessus INET NOT NULL,
  subseco_casus CIDR NOT NULL,
  somniculosus_incidunt_uxor UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
