-- Migration: alter_table_ter_tribuo_assumenda
-- Type: alter_table
-- Generated by stress-generator

ALTER TABLE nisi_laudantium_561 ADD COLUMN alioqui_socius_cupiditate DATE NOT NULL DEFAULT CURRENT_DATE;
