-- Migration: create_view_cinis_capitulus_tersus
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_acerbitas_amplexus_609 AS
SELECT a.id, a.somniculosus, a.terga_vigor_varius, b.id, b.vicissitudo_maiores_subito, b.curriculum_tabgo
FROM animus_deputo_35 a
CROSS JOIN occaecati_dicta_611 b
LIMIT 1000;
