-- Migration: create_table_subito_molestiae_alter
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE calamitas_similique_175 (
  id SERIAL PRIMARY KEY,
  video_apto TIMESTAMP,
  solutio CIDR,
  velit MACADDR NOT NULL,
  velit_valens_termes DOUBLE PRECISION DEFAULT 0.0,
  absque_ambitus DOUBLE PRECISION DEFAULT 0.0,
  solio_caelestis_summa SMALLINT,
  solum_minus_aliquid TIMESTAMP DEFAULT NOW(),
  vapulus_quos INET,
  suppono BOOLEAN,
  viriliter_vergo_corpus TEXT NOT NULL,
  ultio_claustrum_creo CIDR DEFAULT '0.0.0.0/0'::cidr,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
