-- Migration: create_table_vestigium_vox_nobis
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE cena_dolorum_480 (
  id SERIAL PRIMARY KEY,
  victus_caput BOOLEAN NOT NULL DEFAULT false,
  dicta_suasoria_at CIDR UNIQUE,
  spargo_vilis BYTEA,
  patior_cunae CIDR,
  vado_dolor_sed DATE,
  aptus_ullam_vinum TIMESTAMP,
  defleo_summopere_textor JSONB NOT NULL,
  cruentus BYTEA NOT NULL DEFAULT '\x00'::bytea,
  studio TEXT[] NOT NULL,
  suspendo NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
