-- Migration: create_table_suspendo_necessitatibus_beatae
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE demens_aliqua_626 (
  id SERIAL PRIMARY KEY,
  eligendi_vel SMALLINT,
  patria_tollo_curtus BYTEA NOT NULL,
  avarus BOOLEAN,
  possimus_aggredior VARCHAR(255),
  cubo CIDR,
  vicissitudo_accusator_arguo MACADDR,
  vicinus_vulnus_suppellex TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cattus_bos_apto MACADDR,
  temporibus_coma_cunctatio SMALLINT NOT NULL,
  tero INET NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  cervus_crur_422_id INTEGER REFERENCES cervus_crur_422(id)
);
