-- Migration: create_table_aspicio_volutabrum_corrupti
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE thesaurus_quia_468 (
  id SERIAL PRIMARY KEY,
  vitiosus_eius DATE,
  numquam DOUBLE PRECISION NOT NULL,
  vitae UUID NOT NULL,
  temeritas INET,
  conforto TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
