-- Migration: create_table_perspiciatis_curso_capitulus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE voveo_spero_753 (
  id SERIAL PRIMARY KEY,
  adimpleo_tui_assentator REAL DEFAULT 0.0,
  suspendo SMALLINT,
  tot_attero VARCHAR(255),
  texo_adflicto UUID,
  vos_cogito TEXT,
  damnatio TIMESTAMP DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  voluptate_argumentum_270_id INTEGER REFERENCES voluptate_argumentum_270(id)
);
