-- Migration: create_index_crinis_demens_ulterius
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_thesaurus_quia_468_vitiosus_eius_vitae ON thesaurus_quia_468 (vitiosus_eius, vitae);
