-- Migration: trigger_function_audentia_culpa_deludo
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_tenax_viscus_644()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_canto_apto_612_982
  BEFORE UPDATE ON canto_apto_612
  FOR EACH ROW EXECUTE FUNCTION fn_tenax_viscus_644();
