-- Migration: create_table_pauci_ademptio_aggredior
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE tabella_pel_170 (
  id SERIAL PRIMARY KEY,
  vox TEXT DEFAULT 'default_text' UNIQUE,
  suadeo_textor_cauda UUID NOT NULL,
  amplus_terminatio BYTEA NOT NULL DEFAULT '\x00'::bytea,
  cibus_calcar INET NOT NULL,
  aufero_theatrum_voco BYTEA NOT NULL,
  communis TEXT NOT NULL DEFAULT 'default_text',
  denego_vociferor BOOLEAN NOT NULL,
  consectetur_ter DOUBLE PRECISION,
  uredo_utrimque_terra DATE NOT NULL,
  vomer REAL NOT NULL DEFAULT 0.0,
  spectaculum_claro_depraedor INTEGER DEFAULT 0,
  calculus VARCHAR(255) NOT NULL,
  quisquam_verus BIGINT,
  arceo TEXT NOT NULL DEFAULT 'default_text',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
