-- Migration: create_table_accendo_labore_crastinus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE curiositas_denique_376 (
  id SERIAL PRIMARY KEY,
  stillicidium UUID,
  coaegresco_reprehenderit TIMESTAMPTZ UNIQUE,
  absconditus BIGINT,
  caput INT[],
  conculco_beatus TIMESTAMP,
  aedificium_aureus DATE NOT NULL,
  antepono VARCHAR(255) DEFAULT 'default',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
