-- Migration: trigger_function_tonsor_vinculum_coma
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_apto_viridis_329()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on bene_calculus_469 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_bene_calculus_469_662
  AFTER INSERT OR UPDATE OR DELETE ON bene_calculus_469
  FOR EACH ROW EXECUTE FUNCTION fn_apto_viridis_329();
