-- Migration: create_table_pecco_porro_exercitationem
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE accedo_validus_245 (
  id SERIAL PRIMARY KEY,
  unde_vulgaris_claudeo REAL,
  officiis_desparatus DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  denique_aeternus_laborum TIMESTAMPTZ,
  timidus_suadeo_abscido DATE,
  ea BOOLEAN UNIQUE,
  corrigo BYTEA,
  video_adopto REAL NOT NULL,
  sunt VARCHAR(255) NOT NULL,
  supellex REAL NOT NULL DEFAULT 0.0 UNIQUE,
  arcesso_labore INT[] UNIQUE,
  adaugeo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  vigilo_annus SMALLINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
