-- Migration: trigger_function_timor_degero_caecus
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_patior_alii_338()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.id IS NULL THEN
    RAISE EXCEPTION 'id cannot be null on solutio_tendo_265';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_solutio_tendo_265_90
  BEFORE INSERT OR UPDATE ON solutio_tendo_265
  FOR EACH ROW EXECUTE FUNCTION fn_patior_alii_338();
