-- Migration: create_table_adduco_curia_vehemens
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vulgivagus_aperte_796 (
  id SERIAL PRIMARY KEY,
  utrum_cupiditate JSON DEFAULT '{}'::json,
  animus_amplitudo_cunctatio DOUBLE PRECISION NOT NULL DEFAULT 0.0 UNIQUE,
  cavus_ultio_urbanus INET,
  conduco_celebrer INTEGER,
  convoco_saepe MACADDR,
  suspendo_vicinus BOOLEAN NOT NULL DEFAULT false,
  varietas JSON NOT NULL,
  utroque TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  absum_aequus_393_id INTEGER REFERENCES absum_aequus_393(id)
);
