-- Migration: rls_policy_ut_cernuus_aggero
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE tabesco_depono_813 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_tabesco_depono_813_186" ON tabesco_depono_813 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_tabesco_depono_813_909" ON tabesco_depono_813 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_tabesco_depono_813_828" ON tabesco_depono_813 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_tabesco_depono_813_164" ON tabesco_depono_813 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
