-- Migration: create_table_sopor_demens_tergum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE arbitro_acquiro_237 (
  id SERIAL PRIMARY KEY,
  suspendo BOOLEAN,
  coerceo_amo JSONB,
  adduco_quaerat VARCHAR(255) NOT NULL,
  vere_torqueo_cogo NUMERIC(10,2) NOT NULL,
  abduco BYTEA NOT NULL,
  campana MACADDR,
  cinis JSONB NOT NULL,
  coaegresco_animadverto DATE DEFAULT CURRENT_DATE,
  adinventitias_odit JSON UNIQUE,
  a_vaco_accusantium BYTEA,
  tenetur VARCHAR(255) NOT NULL DEFAULT 'default',
  crudelis_blandior_tempore INET NOT NULL,
  cauda_tantillus TIMESTAMP,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
