-- Migration: create_table_custodia_conatus_cunctatio
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE bardus_sumo_809 (
  id SERIAL PRIMARY KEY,
  adduco_aegrus BOOLEAN,
  angustus_termes TIMESTAMP NOT NULL,
  verus_facere_dolorem BOOLEAN NOT NULL,
  antepono_desolo JSON DEFAULT '{}'::json,
  tumultus_cornu_temptatio JSONB DEFAULT '{}'::jsonb,
  vulticulus VARCHAR(255),
  architecto_terreo TIMESTAMPTZ,
  pecus_creta_desolo INET NOT NULL DEFAULT '0.0.0.0'::inet,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
