-- Migration: create_index_cohaero_cunabula_cogito
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_tam_summa_59_perferendis_atrox_coruscus ON tam_summa_59 (perferendis_atrox_coruscus) WHERE perferendis_atrox_coruscus IS NOT NULL;
