-- Migration: create_table_despecto_ultra_tantillus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vigor_infit_788 (
  id SERIAL PRIMARY KEY,
  alii_sed BIGINT,
  speciosus_arcesso_coniuratio TEXT NOT NULL,
  demonstro CIDR DEFAULT '0.0.0.0/0'::cidr,
  apostolus_verus_defendo TIMESTAMP,
  vita BIGINT NOT NULL,
  usus DATE NOT NULL,
  civis_convoco MACADDR DEFAULT '00:00:00:00:00:00'::macaddr,
  adsidue_vulticulus_sub BIGINT,
  cauda TIMESTAMPTZ DEFAULT NOW(),
  tergum_desino_convoco UUID,
  credo JSON NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
