-- Migration: rls_policy_comitatus_argentum_tollo
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE careo_turbo_210 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_careo_turbo_210_772" ON careo_turbo_210 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_careo_turbo_210_948" ON careo_turbo_210 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_careo_turbo_210_116" ON careo_turbo_210 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_careo_turbo_210_335" ON careo_turbo_210 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
