-- Migration: create_index_suffoco_pel_coma
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_spectaculum_tantum_791_eos_quo_subito_aequus_traho_suffoco ON spectaculum_tantum_791 USING gin (vallum);
