-- Migration: create_table_tamisium_tondeo_sollicito
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE solutio_tendo_265 (
  id SERIAL PRIMARY KEY,
  volaticus TIMESTAMPTZ NOT NULL,
  animus NUMERIC(10,2) NOT NULL,
  volo INET,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
