-- Migration: create_table_defaeco_sit_viridis
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE vinum_saepe_877 (
  id SERIAL PRIMARY KEY,
  dolores_spes TEXT[],
  vicinus_cubicularis_viriliter REAL,
  maxime_architecto UUID NOT NULL DEFAULT gen_random_uuid(),
  cupressus BYTEA NOT NULL,
  vesper INET,
  corporis_summisse_adhaero DATE DEFAULT CURRENT_DATE UNIQUE,
  solium INET NOT NULL,
  aspernatur_sunt_temeritas VARCHAR(255) NOT NULL UNIQUE,
  admiratio TIMESTAMP,
  corona_adipisci_coepi JSON DEFAULT '{}'::json,
  vulnus_comprehendo_creber NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
