-- Migration: create_index_tenus_sordeo_ultra
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_bardus_sumo_809_antepono_desolo_architecto_terreo ON bardus_sumo_809 USING gin (antepono_desolo);
