-- Migration: rls_policy_demo_curis_decor
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE canis_adicio_18 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_canis_adicio_18_507" ON canis_adicio_18 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_canis_adicio_18_19" ON canis_adicio_18 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_canis_adicio_18_392" ON canis_adicio_18 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_canis_adicio_18_75" ON canis_adicio_18 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
