-- Migration: create_table_absque_odit_placeat
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE patrocinor_usitas_946 (
  id SERIAL PRIMARY KEY,
  vinco BYTEA NOT NULL DEFAULT '\x00'::bytea,
  sponte_cumque_accendo NUMERIC(10,2),
  tumultus_audio REAL NOT NULL DEFAULT 0.0 UNIQUE,
  aliquam_tamisium INT[] DEFAULT ARRAY[]::INT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
