-- Migration: create_table_dignissimos_utilis_depulso
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE veniam_ulterius_668 (
  id SERIAL PRIMARY KEY,
  audax_aeternus_capto INET,
  eligendi_adversus_tripudio NUMERIC(10,2) DEFAULT 0.00,
  tricesimus_utroque_mollitia JSONB,
  pauper_vapulus_decipio NUMERIC(10,2) NOT NULL,
  doloremque INTEGER,
  paulatim_talus_dicta DOUBLE PRECISION DEFAULT 0.0,
  adipisci_apud BOOLEAN NOT NULL,
  perferendis BOOLEAN UNIQUE,
  blanditiis TEXT,
  dolores_claudeo INT[] DEFAULT ARRAY[]::INT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  vigor_quisquam_335_id INTEGER REFERENCES vigor_quisquam_335(id)
);
