-- Migration: create_index_aptus_voco_trado
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_absum_aequus_393_attonbitus_testimonium_admoneo_hic_sui_coe ON absum_aequus_393 USING gin (laborum_absque_compello);
