-- Migration: trigger_function_appono_acies_argumentum
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_natus_tenuis_289()
RETURNS TRIGGER AS $$
BEGIN
  RAISE LOG 'Audit: % on confero_vestrum_225 id=%', TG_OP, COALESCE(NEW.id::text, OLD.id::text);
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_confero_vestrum_225_409
  AFTER INSERT OR UPDATE OR DELETE ON confero_vestrum_225
  FOR EACH ROW EXECUTE FUNCTION fn_natus_tenuis_289();
