-- Migration: create_table_suspendo_carcer_paens
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE traho_argentum_39 (
  id SERIAL PRIMARY KEY,
  summopere JSON,
  desino_peccatus_cognatus SMALLINT,
  strues_adipisci_confido DATE DEFAULT CURRENT_DATE UNIQUE,
  tabgo_alias_accusator BYTEA,
  audentia_tero TEXT[],
  tabernus_vestigium DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  atqui_rem TIMESTAMPTZ NOT NULL,
  sit TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[] UNIQUE,
  autus CIDR NOT NULL DEFAULT '0.0.0.0/0'::cidr,
  ver JSONB NOT NULL,
  conforto_reiciendis NUMERIC(10,2) DEFAULT 0.00,
  quo_vergo TEXT DEFAULT 'default_text',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
