-- Migration: create_view_illum_ventus_quia
-- Type: create_view
-- Generated by stress-generator

CREATE VIEW vw_desolo_campana_899 AS
SELECT a.id, a.contigo_claudeo_tolero, a.theologus_sol, b.id, b.delectatio_tametsi, b.exercitationem_amita
FROM eaque_utpote_741 a
CROSS JOIN bellum_correptius_485 b
LIMIT 1000;
