-- Migration: create_table_vinco_sapiente_speciosus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE thesaurus_ipsum_397 (
  id SERIAL PRIMARY KEY,
  ars_collum_clam MACADDR NOT NULL,
  mollitia_tristis INT[] UNIQUE,
  civis_cohibeo TIMESTAMP NOT NULL,
  aegrotatio_terra TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  amicitia_thesaurus_179_id INTEGER REFERENCES amicitia_thesaurus_179(id)
);
