-- Migration: create_table_tabesco_beneficium_arbustum
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE maiores_confido_323 (
  id SERIAL PRIMARY KEY,
  peior_ultio_celo JSONB DEFAULT '{}'::jsonb,
  omnis_tabgo JSON DEFAULT '{}'::json,
  ager UUID,
  concedo_temeritas DOUBLE PRECISION NOT NULL UNIQUE,
  coruscus_vilitas_toties NUMERIC(10,2) DEFAULT 0.00,
  clementia_dolorum BIGINT NOT NULL DEFAULT 0,
  esse_surgo_debeo DOUBLE PRECISION,
  nihil_cito TIMESTAMP DEFAULT NOW(),
  amet CIDR,
  deorsum_cohaero_eaque DATE DEFAULT CURRENT_DATE,
  conqueror_sulum TIMESTAMP NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  corpus_dicta_560_id INTEGER REFERENCES corpus_dicta_560(id)
);
