-- Migration: create_table_bos_censura_thymbra
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE derelinquo_curiositas_411 (
  id SERIAL PRIMARY KEY,
  auxilium VARCHAR(255) DEFAULT 'default',
  voluptate SMALLINT UNIQUE,
  addo_vilicus_vapulus JSON,
  adinventitias_adnuo UUID,
  bellum_cruentus_comes DATE,
  deprecator_ubi REAL DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
