-- Migration: create_index_inventore_centum_terror
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_abduco_carbo_510_attero_strenuus_vomer_consectetur_temporib ON abduco_carbo_510 (attero_strenuus, vomer_consectetur, temporibus_architecto) WHERE attero_strenuus IS NOT NULL;
