-- Migration: create_index_xiphias_dapifer_cursus
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_odio_desino_873_defendo ON odio_desino_873 (defendo) WHERE defendo IS NOT NULL;
