-- Migration: trigger_function_videlicet_tantillus_vilis
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_fugiat_vereor_388()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_calamitas_similique_175_829
  BEFORE UPDATE ON calamitas_similique_175
  FOR EACH ROW EXECUTE FUNCTION fn_fugiat_vereor_388();
