-- Migration: create_table_vulnus_curtus_comitatus
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE consequuntur_umerus_396 (
  id SERIAL PRIMARY KEY,
  creptio_veritas INET,
  celebrer UUID,
  officiis BYTEA NOT NULL,
  libero_ipsum_amplus INTEGER DEFAULT 0 UNIQUE,
  adduco_pariatur_fugit TEXT[] DEFAULT ARRAY[]::TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
