-- Migration: trigger_function_vigor_tolero_tracto
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_degusto_curto_897()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_voluptate_argumentum_270_289
  BEFORE UPDATE ON voluptate_argumentum_270
  FOR EACH ROW EXECUTE FUNCTION fn_degusto_curto_897();
