-- Migration: trigger_function_vacuus_amitto_cursus
-- Type: trigger_function
-- Generated by stress-generator


CREATE OR REPLACE FUNCTION fn_suus_delectatio_324()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.abstergo IS NULL THEN
    RAISE EXCEPTION 'abstergo cannot be null on sulum_bellicus_307';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_sulum_bellicus_307_609
  BEFORE INSERT OR UPDATE ON sulum_bellicus_307
  FOR EACH ROW EXECUTE FUNCTION fn_suus_delectatio_324();
