-- Migration: create_table_voluptatem_sol_aveho
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE absum_aequus_393 (
  id SERIAL PRIMARY KEY,
  claro_sub MACADDR NOT NULL DEFAULT '00:00:00:00:00:00'::macaddr,
  carbo TEXT[],
  laborum_absque_compello JSONB UNIQUE,
  crux INTEGER,
  aspicio INTEGER NOT NULL UNIQUE,
  admoneo_hic_sui MACADDR NOT NULL,
  aggero_varius_infit CIDR,
  aggredior_adulescens_caritas BIGINT NOT NULL DEFAULT 0,
  attonbitus_testimonium DOUBLE PRECISION,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  coerceo_suggero_68_id INTEGER REFERENCES coerceo_suggero_68(id)
);
