-- Migration: create_index_valetudo_defetiscor_charisma
-- Type: create_index
-- Generated by stress-generator

CREATE INDEX idx_celer_bellicus_765_ad_advoco_cibo_uxor_repudiandae_cresco ON celer_bellicus_765 (ad_advoco, cibo, uxor_repudiandae_cresco);
