-- Migration: rls_policy_voluptatum_thalassinus_soluta
-- Type: rls_policy
-- Generated by stress-generator

ALTER TABLE fuga_verto_346 ENABLE ROW LEVEL SECURITY;

CREATE POLICY "policy_select_fuga_verto_346_82" ON fuga_verto_346 FOR SELECT TO authenticated USING (auth.uid() IS NOT NULL) ;

CREATE POLICY "policy_insert_fuga_verto_346_992" ON fuga_verto_346 FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_update_fuga_verto_346_157" ON fuga_verto_346 FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "policy_delete_fuga_verto_346_988" ON fuga_verto_346 FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL) ;
