-- Migration: create_table_spiritus_avarus_depulso
-- Type: create_table
-- Generated by stress-generator

CREATE TABLE audax_antea_139 (
  id SERIAL PRIMARY KEY,
  terra_tamen NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  absque_adduco CIDR NOT NULL DEFAULT '0.0.0.0/0'::cidr,
  cohibeo_adfectus_vicissitudo TIMESTAMP,
  centum BOOLEAN NOT NULL DEFAULT false,
  arca_voluntarius_vinitor MACADDR,
  attollo_tener_confido BIGINT,
  vulnero_cubitum NUMERIC(10,2),
  id_tenuis_alii SMALLINT DEFAULT 0,
  accedo_celo JSONB,
  via_territo SMALLINT,
  tactus_quibusdam_vos JSON,
  vita_subiungo_patior UUID,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
